### ISSUE TITLE
[Mobile] textselection bug ,

### ISSUE THREAD

**Issue by demoYang** [singerdmx/flutter-quill#1024]
My issue is about [Mobile]

**QuillEditor set readyonly:true** 

https://user-images.githubusercontent.com/7134823/207216870-35d73c82-b9c6-4b28-af5f-df9319912fa0.mp4

my solution :`  if (ignoreFocus || _keyboardVisible || widget.readOnly) `
<img width="662" alt="image" src="https://user-images.githubusercontent.com/7134823/207217685-6808385e-e46f-4c22-ba13-1c540ec74c8f.png">

**Comment by freshtechtips** [comment]
Please let me know if you still facing this issue or send a pull request to fix it so the others will get your changes as well

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
