### ISSUE TITLE
How to set and get content as HTML? 

### ISSUE THREAD

**Issue by sunnyasr** [singerdmx/flutter-quill#1040]
My issue is about [Web]
My issue is about [Mobile]
My issue is about [Desktop]

I have tried running `example` directory successfully before creating an issue here. 

Please note that we are using <b>latest</b> flutter version in stable channel on branch master. If you are using beta or master channel, or you are not using <b>latest</b> flutter version in stable channel, you may experience error.

**Comment by freshtechtips** [comment]
You need to use a different package for that and get the delta document as json, passing it to the quill HTML converter

Just convert it back from HTML to delta json and parse it

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
