### ISSUE TITLE
[Mobil] how to show link preview?

### ISSUE THREAD

**Issue by Heyholder** [singerdmx/flutter-quill#1059]
My issue is about [Mobile]

I want to show link preview. is there way to show link preview???
if there is not way to show link preview, I will use any_link_preview library. it is needed url.
how to get url from flutter-quill document??

**Comment by freshtechtips** [comment]
This require re-implementing the feature from scratch 

Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
