### ISSUE TITLE
[Desktop] Hidden cursor while typing, which complicates deleting with [BACKSPACE] key.

### ISSUE THREAD

**Issue by izamha** [singerdmx/flutter-quill#1146]
My issue is about [Desktop]

The cursor is hidden while typing which makes it quite hard to delete with [BACKSPACE], unless you manually reposition the cursor and delete one character at a time!

**Comment by Juliotati** [comment]
@izamha This happens when `setState` or `notifyListeners` is called from the client side, usually when the input changes.
It's happening on mobile too.

It's not an issue when you want nothing depends on the text field change.

It becomes more of an issue when a button needs to be enabled or disabled depending on the input; which required calling `setState` or `notifyListeners` depending on the use-case

**Comment by milindgoel15** [comment]
It is indeed an issue when other/native apps do it fine. The cursor stays visible whether you are typing or deleting.

**Comment by viet-tran-0159** [comment]
has anyone resolve this problem yet?

**Comment by AtlasAutocode** [comment]
The current version does not have this problem.
If the problem still exists, please reopen and let us know how to reproduce the program.
