### ISSUE TITLE
[Web] formatSelection with Attribute ignores boolean value

### ISSUE THREAD

**Issue by coryswainston** [singerdmx/flutter-quill#1178]
When I try to update bold, italic, or underline attributes using the controller, I find there's no way to turn OFF the bold, italic, or underline attributes.

```
widget.controller.formatSelection(
    Attribute(
        'bold',
        AttributeScope.INLINE,
        false,
    ),
);
```

This still results in the selection being bold. Even calling this when the selection is NOT bold makes the selection become bold. Whether I place true or false here doesn't seem to make a difference.

**Comment by coryswainston** [comment]
I discovered I can make this work by changing the false value to null. It has solved my problem but still pretty confusing.

**Comment by AtlasAutocode** [comment]
Yes, it is confusing!
The only valid values are `true=bold` and `null=remove-bold`.
value=false is never used, I presume because there is no point having a false attribute.

For processing deltas during operations, this was the chosen methodology.
It would be simpler to have an add-remove concept, but delta processing is extremely complex and having 2 modification paths would be a nightmare to maintain by multiple contributors.

I am closing this issue. If you disagree, please reopen with comments.
