### ISSUE TITLE
Extensions problem

### ISSUE THREAD

**Issue by hallowcard13** [singerdmx/flutter-quill#1238]
> I also encountered the same question，i use this [url](https://github.com/dint-dev/universal_html/issues/76) solve my question

Thank for you reply @bigfox563 , I installed the csslib as mentioned on the link,  but i'm getting error 

../../.pub-cache/hosted/pub.dev/flutter_quill_extensions-0.3.2/lib/embeds/builders.dart:25:10: Error: The method 'ImageEmbedBuilder.build' has fewer positional arguments than those of overridden method 'EmbedBuilder.build'.
builders.dart:25
Could not build the application for the simulator.

Any Ideas how to solve this ?

_Originally posted by @hallowcard13 in https://github.com/singerdmx/flutter-quill/issues/1228#issuecomment-1564373359_

**Comment by candrabisa** [comment]
In object-oriented programming, when a subclass overwrites a method of a superclass (or interface), the subclass must have the same method signature, including the number and type of arguments. In this case, **ImageEmbedBuilder** overwrites the build method of **EmbedBuilder,** but it seems to have fewer arguments.

To solve this problem, you need to ensure that the build method of the **ImageEmbedBuilder** class has the same number and type of arguments as the **EmbedBuilder** build method. If you are working with a library or framework, refer to its documentation to understand the correct method signatures and update your code accordingly.

I will provide the solution. Go to the package class and check and make sure everything that uses the **EmbedBuilder** build method has the same argument.

Check this:
![Screenshot_20230527_115855](https://github.com/singerdmx/flutter-quill/assets/61926920/412fee47-2308-4dcc-b194-9053f93f8dae) 
![Screenshot_20230527_120114](https://github.com/singerdmx/flutter-quill/assets/61926920/e0a639a4-65ac-4966-ac6f-1fda127f9b37)

In my case, there was no **TextStyle** in the **VideoEmbedBuilder** class so I added my own, and the problem was solved.

**Comment by candrabisa** [comment]
In object-oriented programming, when a subclass overwrites a method of a superclass (or interface), the subclass must have the same method signature, including the number and type of arguments. In this case, **ImageEmbedBuilder** overwrites the build method of **EmbedBuilder,** but it seems to have fewer arguments.

To solve this problem, you need to ensure that the build method of the **ImageEmbedBuilder** class has the same number and type of arguments as the **EmbedBuilder** build method. 

I will provide the solution. Go to the package class and check and make sure everything that uses the **EmbedBuilder** build method has the same argument.

Check this:
![Screenshot_20230527_115855](https://github.com/singerdmx/flutter-quill/assets/61926920/ea21c4fe-da1f-42b9-afc7-4bcc4a8b9f40)
![Screenshot_20230527_121553](https://github.com/singerdmx/flutter-quill/assets/61926920/c97c5456-06f7-4acf-a873-9088b870a377)

In my case, there was no **TextStyle** in the **ImageEmbedBuilder** class so I added my own and the problem was solved.

**Comment by hallowcard13** [comment]
Thank you for your reply, the thing is that been using the package without
problems , after the flutter update thr probelm occurs, i havent done what
you have suggested either and on the documentation it was clear that it
will install the extension for video amd image embeding

**Comment by hallowcard13** [comment]
If you could give a sample here since im starting using this package while learning flutter

**Comment by hallowcard13** [comment]
There is as PR for this #1233 but it's not publish on flutter pub website i think since if you install the extension package the issue is still persist, So temporary fix for me is to copy the changes on that PR #1233

**Comment by chrisskeddy** [comment]
Please can someone please make a new release to flutter pub website. The flutter_quill has a version of 7.2.10 which has code that fixes this issue. https://pub.dev/packages/flutter_quill/

Now we need the flutter_quill_extensions to get an update for the same issue.
https://pub.dev/packages/flutter_quill_extensions
The last update for this package was over a month ago so the extensions still have this error.

**Comment by singerdmx** [comment]
@simonpham

**Comment by simonpham** [comment]
@singerdmx I'm free. Let me take a look if I can help.

**Comment by singerdmx** [comment]
actually I don't own package https://pub.dev/packages/flutter_quill_extensions
@Jon-Salmon owns it

**Comment by simonpham** [comment]
@chrisskeddy
You can use it directly (update commit hash in ref if you need another version):
```yaml
  flutter_quill_extensions:
    git:
      url: https://github.com/singerdmx/flutter-quill.git
      path: flutter_quill_extensions
      ref: 8e54adee875caf2eccb757d2863c6d7059883509
```
Current ref points to latest version 7.2.11: [8e54adee875caf2eccb757d2863c6d7059883509](https://github.com/singerdmx/flutter-quill/commit/8e54adee875caf2eccb757d2863c6d7059883509)

**Comment by Jon-Salmon** [comment]
Update has been published
