### ISSUE TITLE
Incompatibility of text styling attributes and lists

### ISSUE THREAD

**Issue by EgorK0rshun** [singerdmx/flutter-quill#1258]
After applying AlignAttribute, the left side of the lists (icons) remain in the same position. After applying HeaderAttribute, the icons for the list disappear altogether. In example you can find this bugs.

**Comment by singerdmx** [comment]
Will take a look

**Comment by singerdmx** [comment]
Is it for mobile?

**Comment by EgorK0rshun** [comment]
@singerdmx , yes, for mobile

**Comment by EgorK0rshun** [comment]
any updates?
I had to remove the lists to avoid such a problem. I would like to use the library to its fullest, but this bug does not allow it.

**Comment by EgorK0rshun** [comment]
any updates?

**Comment by CatHood0** [comment]
Which version are you using? This should be fixed at the current version

**Comment by CatHood0** [comment]
If your issue is related with the `Alignment,` you need to know the only way to change the position of the icons on the lists is chaning the direction to `RTL` of the `Line`. By default (at the current version) the widgets in the editor listen the `Directionality` from the language system or the `Direction` from the attributes of the `Line`
