### ISSUE TITLE
[Mobile] Selection handles don't change selection

### ISSUE THREAD

**Issue by Alspb** [singerdmx/flutter-quill#1297]
My issue is about [Mobile] (Android).

Currently, to change selection user should drag one of its ends, not the correspondent selection handle. So, in fact selection handles don't really do anything.
Example: select a word on one line and try to expand the selection keeping it on the same line using handles. But it turns out that the next line also becomes selected.

**Comment by ellet0** [comment]
> @ellet0, could you please take a look?

Sorry, I'm no longer an active maintainer
I will only fix the bugs I can fix right away, including any bug that I might cause

Or only update the project to work with the latest version of Flutter

I might be back in the future (unlikely) for now. I can't understand the base source code because it's not clear

I tried making many changes, like spliting code into parts for the raw editor widget

There were many updates, but it didn't help

This project requires more time than I have, and I only updated it because I wanted, but the community doesn't seem to appreciate anything at all

All that they can do is blaming and waste other people time by complaining

I was interested because I had an app that required the editor, but recently, I quit the development of the app, so I have no reason to work or do anything with this project 

I will try to care only about myself just like the community did (most of them)

**Comment by CatHood0** [comment]
I'll close it since was fixed.
