### ISSUE TITLE
[Web] Cant add html header tags to the initial text 

### ISSUE THREAD

**Issue by MayaBloodsAI** [singerdmx/flutter-quill#1406]
My issue is about [Web]

Everything working great (;

Only problem when I try to ad initial text to the editor with header I get an assertion:

![image](https://github.com/singerdmx/flutter-quill/assets/98014743/358dbab3-8398-490c-ab3b-ad6c0220bccb)

My code:

`
final Delta delta Delta.fromJson([{'insert': 'Hello '},{'insert': 'This is colorful\n','attributes': { 'header' : 1}},]);
_controller = QuillController(
      document:  Document.fromDelta(delta),
      selection: TextSelection.collapsed(offset: 0),
    );
`

**Comment by JouseLovic** [comment]
You have a issue here: `{'header':1}`

When you write in delta, you must place any insertion, or attribute definition inside the quotes. Something like:

`r"{"insert":"any word","attributes":{"align":"center", "bold":"true", "header":"2"}}"
`

The solution is obvious now:

`final Delta delta Delta.fromJson([{'insert': 'Hello '},{'insert': 'This is colorful\n','attributes': { 'header' : '1'}},]); _controller = QuillController(document: Document.fromDelta(delta), selection: TextSelection.collapsed(offset: 0),);`

Delta only correctly recognizes attributes or insertions when they are around quotes

And a piece of advice. When you are going to insert a "\n" the best thing you can do is put r just before opening the string (something like: `r"{"insert":"\n"}"`), since sometimes it causes problems because it does not It recognizes the line break (although I couldn't tell if it was just my mistake or it has already happened to other people). It's just a piece of advice, if that error hasn't happened to you, I'm happy for you.

**Comment by MayaBloodsAI** [comment]
Hi Jouse,

I still get the same error..
Another thing when I remove the assertion everything working just fine with the header..

this what I changed

`
@override
  void applyStyle(Style value) {
    assert(!value.isInline || !value.isIgnored || !value.isEmpty,
        'Unable to apply Style to leaf: $value');
    super.applyStyle(value);
  }
`
