### ISSUE TITLE
[Mobile] QuillCustomButton icon no longer working

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1459]
`icon` field in `QuillCustomButton` is no longer working.  If this has been changed, documentation has not been updated to tell us how to migrate this.  Documentation still refers to `icon`

**Comment by freshtechtips** [comment]
> `icon` field in `QuillCustomButton` is no longer working. If this has been changed, documentation has not been updated to tell us how to migrate this. Documentation still refers to `icon`

Hi, yes the documentation hasn't been updated yet because we are working on refactoring the configurations

but we mention that is the next few releases just for a few days is not stable yet but it will be in less than three weeks

<img width="1297" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/73608287/4d26c0ec-7408-4a13-b22a-bbd0f74f1c2f">

**Comment by freshtechtips** [comment]
The `icon` property has been renamed to `iconData` to be more clear and concise so we can customize things in the future more

<img width="1343" alt="image" src="https://github.com/singerdmx/flutter-quill/assets/73608287/d383b86e-e88e-4cd4-9cb7-ddb034e6abbe">


since it's icon data and not a widget

**Comment by freshtechtips** [comment]
> `icon` field in `QuillCustomButton` is no longer working. If this has been changed, documentation has not been updated to tell us how to migrate this. Documentation still refers to `icon`

I just checked this issue and it has been solved, if you still face this issue or any others
Do not hesitate to contact us

**Comment by hardikthakkar2208** [comment]
QuillCustomButton icon no longer working, we face same issue after selection not able to see selected color
