### ISSUE TITLE
[Web] or [Mobile] or [Desktop] 

### ISSUE THREAD

**Issue by Best01010101** [singerdmx/flutter-quill#1482]
i have to create account on the github just so i contact the support!! why!!!

i tried this flutter package in 2022 and it was have bugs all over the place!!! issues!!! 

now i upgrade package and i noticed everything changed and the build didn't successful it give me gradle bugs

whyy?!!! who is the stupi**d genius ask for this update??!!! It didn't change anything and the design is just shi**ty as ever

 extensions package don't work any more!!

who ask the update?!!! i would like to met them
i have feelings that we will get along

**Comment by freshtechtips** [comment]
Hi, thank you for the report

We decided to refactor the package because of the old way of setting up the configurations
 which makes it hard for us to manage everything add new features and provide more customizations

the refactoring process is just the start and we will plan on improving the package to the next level as soon as we can.

I did suggest it as a start and the others agreed on the same idea

Currently I'm not working on the package and can't do anything because of my internet and it will be blocked for almost half the day for a while so I can't do much

Please notice gradle issues you are facing is not related the issues you are facing

it trying to build the android binary with the flutter engine and dart code and it give you the issues you saw

But I can see you already fixed it yourself since you try out the new version

it's helpful to have a github account to create issues and contribute to other projects so the open source projects will continue thank to the efforts we all made

as for the flutter_quill_extensions it might not have the latest updates so please use [fresh_quill_extensions](https://pub.dev/packages/fresh_quill_extensions) as temporary alternative

as for the design now you can customize a lot of things and we will add more options in the near future to fit your needs

**Comment by freshtechtips** [comment]
This issue you created is quite generic and it's not specific to something we can debug
but we are working on fix all the bugs and add more improvements

so I will have to close this issue

but If you still facing any other issues or have any other questions, feel free to contact us on GitHub

**Comment by freshtechtips** [comment]
> > This issue you created is quite generic and it's not specific to something we can debug but we are working on fix all the bugs and add more improvements
> > so I will have to close this issue
> > but If you still facing any other issues or have any other questions, feel free to contact us on GitHub
> 
> listen here little shi*t
> 
> DONT THINK ALL THE WORLD IS OVER YOU
> 
> you think you are so special and calling things fresh with your fu***ed ideas in your little mind you are nothing!!!

Hi again, I'm in the middle of another tasks, give me some time and I will get back to you
