### ISSUE TITLE
Why have you deleted versions changelog below 7.10.0 ?

### ISSUE THREAD

**Issue by MagTuxGit** [singerdmx/flutter-quill#1551]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

![Screenshot 2023-11-23 at 12 00 29](https://github.com/singerdmx/flutter-quill/assets/5296407/39e4d7a3-82f8-49c8-bf6c-2c0be2ff933d)

**Comment by freshtechtips** [comment]
Hi, I don't remember we have deleted the previous versions but from now on when we release new version we will add a tag in the tags and versions in GitHub repo to help tracking the changes

If you have any questions feel free to ask us on GitHub at any time.

**Comment by MagTuxGit** [comment]
You don't need to remember. Just look at changelog on pub.dev. There are no changelogs for versions between 7.1 and 7.10

**Comment by freshtechtips** [comment]
> You don't need to remember. Just look at changelog on pub.dev. There are no changelogs for versions between 7.1 and 7.10

What I meant is that I'm not sure about this change. Yes, I have fixed typos and changed a few things, but I didn't remove anything 

Perhaps it was a mistake, but I don't dee it that important, we already changed the way we manging different versions as I mentioned above

Why do you want to see the older versions change anyway?? It's no longer supported, and most developers have already moved to the new one

If you still want to see it, I can track it in git commit history because I'm aware of the revent changes in the past few months

**Comment by MagTuxGit** [comment]
Changelogs for versions 7.5.0-7.9.0 had important information for migration and I haven't migrated yet.
