### ISSUE TITLE
Hardcoded wrap run alignment

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#1588]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.x

### Other Flutter Quill packages versions

Quill 9.x

### Steps to reproduce

All this effort at wasted customization and there is a hardcoded runalignment on the toolbar wrap of '4'.  

Why is that?

We cannot accurately control the space between icon widgets and then we are also force to maintain a blank Sizedbox wasting memory on top of it.

### Expected results

Remove a run alignment int he wrap when you have already wasted so much resources on the spacer widget

### Actual results

Something more sensible

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by freshtechtips** [comment]
Are you talking about the `QuillSimpleToolbar`? As we said in the PR, we want to confirm with Quill js

We want to encourage the developer to create his own toolbar just like React Quill or quill js

The final decision is from @singerdmx 

You can use the `QuillToolbar` and use the buttons and customize them using the `childBuilder`

Besides I think you are talking about changes from the old versions before 8.0.0
because it was like that when the library first started so it's not related to the customization options

**Comment by freshtechtips** [comment]
That's not really a bug but I just added the option to change the value

It was with no customization option in the first place
I didn't touch it

The commit is to the dev branch

If you have any other questions feel free to ask us at any time.
