### ISSUE TITLE
dart_quill_delta version 0.0.1 is used instead of 9.2.10

### ISSUE THREAD

**Issue by flodaniel** [singerdmx/flutter-quill#1715]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.10

### Steps to reproduce

1. Install flutter_quill
2. Check version of dart_quill_delta in pubspec.lock

### Expected results

Version 9.2.10 is the latest version of `dart_quill_delta` which I would expect to be used

### Actual results

Version 0.0.1 is used instead

### Code sample

<details><summary>Code sample</summary>

```dart
  dart_quill_delta:
    dependency: transitive
    description:
      name: dart_quill_delta
      sha256: "733eb31821ceb45f43c47bf7f8c5a8aaee39550c0985ed38ff440e8ea5353e2d"
      url: "https://pub.dev"
    source: hosted
    version: "0.0.1"
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ellet0** [comment]
Currently flutter quill require the minimum version of quill delta is 0.0.1 and there is no reason to bump the version to the latest version and require all users to use the latest version

Only one small change, it hasn't been changed since the old maintainers got it from another package and did some changes to work with flutter quill

**Comment by ellet0** [comment]
It's not a bug
