### ISSUE TITLE
could not compile `super_native_extensions` (lib) due to 58 previous errors

### ISSUE THREAD

**Issue by JarrenPoh** [singerdmx/flutter-quill#1749]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.2.12

### Steps to reproduce

1. add flutter_quill: ^9.2.12
2. run flutter pub get 
3. run app

### Expected results

open the app 

### Actual results

Failed to build iOS app
Could not build the precompiled application for the device.

in Xcode shows:
could not compile `super_native_extensions` (lib) due to 58 previous errors

### Code sample

<details><summary>Code sample</summary>

no code

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

no details

</details>

### Logs

<details><summary>Logs</summary>

Launching lib/main.dart on xxx in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 9N58JY7V33
Xcode build done.                                           21.9s
Failed to build iOS app
Could not build the precompiled application for the device.

</details>

**Comment by PcolBP** [comment]
Try to install newest rust, its required by super_clipboard:

https://www.rust-lang.org/tools/install

Overall I think that super_clipboard should be optional library, right now upgrading quill brings with it rust and other stuff that require work, for me ci/cd is not working after that, I can compile app on local machine but deploy is now working due to that :/

**Comment by ellet0** [comment]
Thank you for the report. This should be fixed in `9.4.x` by moving the usages of `super_clipboard` to `flutter_quill_extensions`
