### ISSUE TITLE
The font size not show in html when I convert to html

### ISSUE THREAD

**Issue by Terriermon** [singerdmx/flutter-quill#1791]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I want to convert document to html, but the html not show fontSize attributes when I changed the fontSize. And I convert to json it will show fontSize

html: `<p>Wrtyuuuuu<strong>rcvjiikn</strong>uoonbbbnn</p>`
json: `[{insert: Wrtyuuuuu}, {insert: rcvjiikn, attributes: {size: 22.0, bold: true}}, {insert: uoonbbbnn, attributes: {size: 28.0}}]`

**Comment by hodfords-khai-mobile** [comment]
same issue

**Comment by CatHood0** [comment]
The issue comes from Vsc_quill_delta_to_html. You need to pass a custom `ConverterOptions` with you own `inlineStyles` implementation. This works for me

**Comment by CatHood0** [comment]
This issue is already solved by the `Vsc_quill_delta_to_html`. Here is his ### ### answer:

By default, `QuillDeltaToHtmlConverter` uses `defaultInlineStyles` (in `op_to_html_converter.dart`) to convert the Quill size attribute - this handles the semantic sizes: `small` `large` and `huge`. `defaultInlineStyles` has a map that defines how to convert one of these `sizes` to a CSS style.

If you want to use a `size` value that is different from `small` `large` or `huge`, you have to define your converter to handle it, like below.
```dart
      converter = QuillDeltaToHtmlConverter(
        delta,
        ConverterOptions(
          converterOptions: OpConverterOptions(
            inlineStylesFlag: true,
            inlineStyles: InlineStyles({
              ...defaultInlineStyles.attrs,
              'size': InlineStyleType(
                fn: (value, _) => 'font-size: ${value}px',
              ),
            }),
          ),
        ),
      );
```
`InlineStyles` takes either a map to define an explicit mapping of a value to a CSS style, or a fn - like in the example above - which converts an arbitrary value to a CSS style.
