### ISSUE TITLE
white text color by default and impossible to change

### ISSUE THREAD

**Issue by darkomenx** [singerdmx/flutter-quill#1827]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.1.0

### Steps to reproduce

1/ just install package
2/ and this basic implementation into Column flutter widget like that : 

```
QuillToolbar.simple(
            configurations: QuillSimpleToolbarConfigurations(
              controller: _controller,
              sharedConfigurations: const QuillSharedConfigurations(
                locale: Locale('fr'),
              ),
            ),
          ),
          Expanded(
            child: QuillEditor.basic(
              configurations: QuillEditorConfigurations(
                customStyles: const DefaultStyles(color: Colors.black, placeHolder: DefaultTextBlockStyle(TextStyle(color: Colors.black, fontSize: 20), VerticalSpacing(5, 5), VerticalSpacing(5, 5), null)),
                customStyleBuilder: (e) { return const TextStyle(fontSize: 12, color: Colors.black); },
                controller: _controller,
                readOnly: false,
                sharedConfigurations: const QuillSharedConfigurations(
                  locale: Locale('fr'),
                ),
              ),
            ),
          )
```

You can view that I configure all the textStyle config into black color. But nothing change.

### Expected results

My Quill widget editor is rendering with background color white then I need to textStyle color is black

### Actual results

The Quill widget editor is rendering my textStyle color in white.
I can't view the text that I typed...

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
customStyleBuilder is designed to allow customization of TextStyles for **attributes**.
Plain text does not have an attribute so custom is not called.

You can see this if you select your text and apply the bold attribute and now your builder will be called.
You need to be aware that customStyleBuilder must return **ALL** styles and not just color.
In this example your text size will be small because fontsize was not set.

I assume your intent is to change the default style for everything and that is not possible at present.
The best you can do (at present) is to use 'customStyles' to set the styles individually.
