### ISSUE TITLE
how i can exclude device_info_plus 

### ISSUE THREAD

**Issue by samih93** [singerdmx/flutter-quill#1833]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

how i can exclude device_info_plus

**Comment by ellet0** [comment]
Unfortunately there is no way since the editor depends on it, the solution would be that we extract all the plugins code into a separated package that implements an interface that we create in the core package and requiring to implement the interface when using the core package or without nothing when using the new package that include everything of the core package + implementing the interface with the plugins code

so users can define their own solutions or use completely different package but this will require the user/developer some work to get it done

**Comment by EchoEllet** [comment]
Issue fixed in [10.5.15-dev.0](https://pub.dev/packages/flutter_quill/versions/10.5.15-dev.0).

The `device_info_plus` plugin has been removed and is no longer a dependency of `flutter_quill`
