### ISSUE TITLE
Embed Reloads on Cmd Key Press in google chrome

### ISSUE THREAD

**Issue by ilicina2** [singerdmx/flutter-quill#1835]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.4

### Steps to reproduce

1. Open the example app on a macOS device.
2. Navigate to a part of the app where embedded content (e.g., a video) is displayed.
3. Press the Cmd key.
4. Observe that the embedded content reloads.

### Expected results

The embedded content should not reload or refresh when the Cmd key is pressed, as this disrupts the user experience.

### Actual results

Pressing the Cmd key causes the embedded content to reload.

### Code sample

Check example app

### Screenshots or Video

https://github.com/singerdmx/flutter-quill/assets/149594833/2c02ac39-d464-4922-8e22-391c4703b946

**Comment by ellet0** [comment]
Unfortunately there are a lot of performance and user experience issues in the embed widgets and that's nothing new, see this related [issue](https://github.com/singerdmx/flutter-quill/discussions/178)

**Comment by AtlasAutocode** [comment]
This may be related to a similar problem I had with resizing the editor window causing an embedded image to flash.

If I remember correctly, the quill extensions module loaded images that were cached and that prevented the flashing effect.
I could not use the extensions because I needed the actual image bytes to be embedded. The quill extensions embedded a file link which would not work when the quill document was opened on another computer.

My solution was to provide my own image cache so that the original image bytes did not have to be converted to an Image each time and that eliminated the flashing.

You may be able to create a similar cache mechanism to prevent the flashing.

If anyone has a better solution, that would be great!

**Comment by AtlasAutocode** [comment]
Closed as no response from OP.
Presume issue resolved.
You can reopen this issue.

**Comment by EchoEllet** [comment]
> Closed as no response from OP.
> Presume issue resolved.
> You can reopen this issue.

There is a similar issue on desktop shortcuts that makes the editor unusable, I never really had the time or the chance to investigate the bug, I suggest keeping it open even if it will be open longer.

I previously closed a lot of issues that we didn't receive any response or any interaction with the issue, though some of them still exist until now.
