### ISSUE TITLE
Need  letterSpacing ,wordSpacing & text height  features Like available in flutter TextStyle

### ISSUE THREAD

**Issue by mrwebbeast** [singerdmx/flutter-quill#1844]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

These features like   letterSpacing ,wordSpacing & text height  are use full in many use cases just like google docs and i also requires some kind of features in my app ..

Thank You 

### Proposal

Need  letterSpacing ,wordSpacing & text height  features Like available in flutter TextStyle

`   
        const Text(
                                'Screens',
                                style: TextStyle(
                                  color: primaryColor,
                                  fontSize: 22,
                                  fontWeight: FontWeight.w600,
                                  height: 2,
                                  letterSpacing: 5,
                                  wordSpacing: 2,
                                ),
`

**Comment by kairan77** [comment]
This would result in breaking changes in terms of style configuration, I would argue against such a feature in the library.

My main reasons being:

1. Now style is passed as a configuration to the editor fixed on each 'css class', making  letterSpacing ,wordSpacing & text height configurable per fragment, would result in massive breaking change, it also makes dimension calculation much more difficult for rendering positions of objects such as inline embed accurately.
2. Flutter quill is a productivity tool NOT a creation tool, it should optimize towards overall usage efficiency/productivity. Introducing productivity reduction features such as those mentioned (I would also include font size in this category) is against its design goal. Checkout apple/google's UI design guidelines, you soon realize given any specific device /screen resolution /a particular font-category ( such as heading1, heading2, body, quote etc), there is really ONLY ONE setting that is ever optimal for comfortable viewing, any deviation from this very specific optimal setting is ergonomically inefficient. These decisions should be made by coders at design time and not by users at runtime, allowing users to configure these settings in a productivity tool is wasting users' time.
3. Quill can not aim to be a fully fledged creation tool because the underlying metadata (delta/mark down) format is not turing complete. Many features such as excel/word style tables can never be properly implemented without smuggling/encoding some sort of extensions (ie. xml, latex, or other turing complete metadata format) into the poor delta/markdown format.
4. quill is like a hammer or chisel, you use it to chip away things, if you need a scissor for some fancy origami work, then it's probably better to find a scissor to use in the first place. makeshift scissors will never be good enough.

**Comment by CatHood0** [comment]
I can solve your problem to line spacing. I make a custom block attribute that makes this
