### ISSUE TITLE
[Bug in Web] Rejecting promise with error

### ISSUE THREAD

**Issue by Bankzhy** [singerdmx/flutter-quill#1888]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.3.19

### Steps to reproduce

1. Add the following to pubsec.yaml
  flutter_quill: 9.3.19
  flutter_quill_extensions: 9.3.19
 2. Run the main.dart in Web platform

### Expected results

The app build success.

### Actual results

I am using the flutter_quill and flutter_quill_extensions in our project.
It can't be biuld in Web platform. The error:[**Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')**]

The web page is totally white and show nothing.

We have both tested in Flutter 3.19.5 and 3.22.1.
 

### Code sample

<details><summary>Code sample</summary>

```dart
  flutter_quill: 9.3.19
  flutter_quill_extensions: 9.3.19
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AnithaB05** [comment]
I too get this error - Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
I am using flutter_quill 9.3.18 in web.
Any help is much appreciated.

Attached is the error screen shot:
<img width="913" alt="flutter_quill_error2" src="https://github.com/singerdmx/flutter-quill/assets/140070723/11bd7022-2e0c-44d5-901c-788b610f2a22">
<img width="905" alt="flutter_quill_error1" src="https://github.com/singerdmx/flutter-quill/assets/140070723/0de4e86c-473c-4577-9571-9ecb6f0e0f86">

**Comment by Bankzhy** [comment]
I have found the solution, may be you can try. just add the following code to the **[your project path]\web\index.html**

  <script
          type="application/javascript"
          src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js"
          defer
  ></script>


remenber to add it to the top of all <script>

**Comment by Bankzhy** [comment]
Solution founded

**Comment by MarpinLL** [comment]
Hi

Do you know if this bug has been fixed in the latest versions of flutter_quill? It would be helpful to know if adding this script is still necessary or if the updates have resolved the issue.

Thank you.

**Comment by EchoEllet** [comment]
It's a requirement of [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) which included by [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter)

Which is needed by `flutter_quill_extensions` and documented in [Platform Specific Configurations](https://pub.dev/packages/flutter_quill_extensions#-platform-specific-configurations)

That's why I suggested to discount the support of YouTube video support in #2276. Instead should be possible to implement in the user project without changes directly in this repo.

Loading YouTube videos directly by download URLs without using their iframe is against their terms of service (see #1916), loading iframe requires webview, and webview is not natively supported on Flutter and require platform plugin, having webview in the editor as a embed widget caused many issues and bugs even when not interacting with YouTube Video.

**Comment by MarpinLL** [comment]
Thank you very much for your response.

**Comment by EchoEllet** [comment]
You're welcome, I'm looking for your feedback about whether you prefer to not have YouTube support built-in as part of `flutter_quill_extensions` at the price of flexibility and avoid many issues for both the user and developer.  See #2284

**Comment by EchoEllet** [comment]
For anyone facing this issue, refer to [flutter_inappwebview installation](https://pub.dev/packages/flutter_inappwebview#installation) section for web instructions.

I did reopen this issue as it should not be a requirement of `flutter_quill_extensions` and should only require platform-specific configuration when needed.
