### ISSUE TITLE
Using `flutter_quill` requires installing `Rust`?

### ISSUE THREAD

**Issue by SlickSlime** [singerdmx/flutter-quill#1913]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I am using:
```yaml
flutter_quill: ^9.3.11
```

I was getting the following error on building for iOS app
```
Error (Xcode): failed to parse manifest at `/path/to/something/.pub-cache/hosted/pub.dev/super_native_extensions-0.8.16/rust/Cargo.toml`
/path/to/something/ios/Pods/SEVERE:0:0
```

After about an hour of searching the web, thanks to https://github.com/singerdmx/flutter-quill/issues/1749#issuecomment-1969313369 I was able to install Rust on my Mac and fix the issue.

**Suggestion**
Please include in the main README file that user needs to download Rust using following command:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by ellet0** [comment]
Thank you for the report, this should be fixed in `9.4.x` by moving the `super_clipboard` implementation to `flutter_quill_extensions`

> Suggestion
Please include in the main README file that user needs to download Rust using following command:

This information can get outdated really quickly, which is why we pointed `super_clipboard` Readme with a link, we already suggested reading the plugin page to know the requirements.
