### ISSUE TITLE
Underline Styles 

### ISSUE THREAD

**Issue by adrianHerreraa** [singerdmx/flutter-quill#1917]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi, the issue is that when I write styles like underline, it takes it correctly when editing it, when saving the HTML value has something similar to `<p><u>Underline</u></p>, ` but when returning or setting that direct value in the controller does not work, it takes it as a simple paragraph `<p>` and does not assign the corresponding style. Can anyone guide me please?.

**Comment by AtlasAutocode** [comment]
The current code used to import HTML uses html2md which converts html to Markdown and then to Quill Delta.
Since there is no markdown code for underline this style will be ignored.
The only way to solve this problem would be to rewrite the html converter to convert directly to Delta (or json?)
Same answer applies to Issue 1947 sub/sup.

**Comment by CatHood0** [comment]
I notice of this behavior, and i trying to solve it
