### ISSUE TITLE
Is there any way to set the default text style?

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1925]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

I tried this
```dart
_controller.formatTextStyle(0, 0, Style.fromJson({'color': '#fcba03', 'size': 24.0})); 
```

But once the user removes the first character, the text style is reverted.
I think this is similar to #1778

**Comment by geronimol** [comment]
As a workaround, for now I added a listener to handle the change like so:

initState:
```dart
_controller.addListener(onTextChangeListener);
```

dispose:
```dart
_controller.removeListener(onTextChangeListener);
```

the listener:
```dart
onTextChangeListener() {
    final isEmpty = _controller.document.isEmpty();
    final isBlank = _controller.document.toPlainText().trim().isEmpty;
    if (isEmpty || isBlank) {
      _controller.removeListener(onTextChangeListener);
      setDefaultTextStyle();
      _controller.addListener(onTextChangeListener);
    }
  }
```

```dart
setDefaultTextStyle() {
    if (widget.defaultTextStyle != null) {
      _controller.formatTextStyle(
          0,
          0,
          Style.fromJson({
            'font': widget.defaultTextStyle!.fontFamily,
            'size': widget.defaultTextStyle!.fontSize,
            'bold': widget.defaultTextStyle!.fontWeight == FontWeight.bold ? true : null,
          }));
    }
  }
```

**Comment by AtlasAutocode** [comment]
Setting the default text style looks to be possible using QuillEditorConfigurations.customStyles.
In the example app code in file lib\screens\quill\samples\my_quill_editor.dart line 46 shows how the h1 style is set. You could add a style for paragraph:
> customStyles: const DefaultStyles(
       paragraph: DefaultTextBlockStyle(TextStyle(color: Colors.purple), VerticalSpacing(0,0), VerticalSpacing(0, 0), null),),

Code snippet:
>   Widget build(BuildContext context) {
          **final defaultTextStyle = DefaultTextStyle.of(context);**
         return QuillEditor(
                  **configurations**: configurations.copyWith(
                            **customStyles**:  DefaultStyles(
                            **paragraph**: DefaultTextBlockStyle ( defaultTextStyle.style.copyWith(color: Colors.purple,),

(Sorry for lack of formatting - I haven't figured out how to indent in code block!)

**Comment by geronimol** [comment]
@AtlasAutocode Thanks for the fix. It seems to work to keep styles, but the problem still happens when using a custom font, it changes it to normal. 

![Captura de pantalla 2024-07-01 a la(s) 11 09 17](https://github.com/singerdmx/flutter-quill/assets/56521222/6cf3dac3-d51d-4834-8b2b-8957b8f8d958)

**Comment by geronimol** [comment]
@AtlasAutocode I already tried that before the above workaround. It changes the style on the editor, but it does not save it when you do something like `_controller.document.toDelta().toJson()`.

**Comment by AtlasAutocode** [comment]
OK, I think there may be 2 completely separate issues here.

The first is the display in the editor and that works as discussed. Json can be saved and reloaded and will obey the styles you have set.

The second is exporting the data from the editor, presumably with the intent of importing into another application. (It would be helpful if you can share what you intend to do with the json.)

In looking at the output from toDelta, I see it contains attributes (by name) but it does not include any styles associated with each attribute.

Am I correct that you want the entire style details to be exported from the editor? If this is the case then I would guess that the problem is how you handle the deltas.

I can see several possibilities:
1. Explore exporting as PDF or HTML
2. Implement your own replacement for the toJson function to output the full styles rather than just the attribute name.
3. Something appropriate to your intended use?

**Comment by geronimol** [comment]
What I was expecting is an easy way to set the default style on the editor. E.g: Set default color to red.

Using the above code(`customStyles`), it shows the text in red color in the editor:
![Captura de pantalla 2024-07-01 a la(s) 18 32 30](https://github.com/singerdmx/flutter-quill/assets/56521222/8c21748c-13de-48fa-ac1a-6e8a751ca53f)
but then if I continue editing and add another color like so:
![Captura de pantalla 2024-07-01 a la(s) 18 33 32](https://github.com/singerdmx/flutter-quill/assets/56521222/015bd71d-312c-48ff-83cf-2639eee8f3ce)
and then when I save to delta(forget about Json for now) using `_controller.document.toDelta()`
it is saved like so:
![Captura de pantalla 2024-07-01 a la(s) 18 36 05](https://github.com/singerdmx/flutter-quill/assets/56521222/570e4e00-01d3-477f-b623-8b2fb8cc0a35)

---

Now regarding of what I am doing with the Json: I am saving it to a database, so then I can show the rich text in `readOnly` mode in the same way it was saved. Everything works fine. Previously I was using HTML, but I was getting too many problems in the conversions, so that is why I changed delta json.

**Comment by AtlasAutocode** [comment]
I took one of my files with normal black text saved using delta+json.
I set the QuillEditor custom style for paragraph to red.
Loading the file now showed the text in red.
I added some blue text and saved.
Reloading showed the original text in red and the added blue text.

Next, I changed the paragraph style to green and restarted the program.
My file now showed with the original text in green and the added blue text.

The default display color is obeying what is set in the custom style. The saved file will not show any color since it will show as whatever the default is set for. (I assume your viewer is set with the same custom style as that used to generate the data.)

Can you provide the json for each of your 3 images?

**Comment by geronimol** [comment]
> (I assume your viewer is set with the same custom style as that used to generate the data.)

Sorry, I was displaying the saved text in a new editor(without `customStyles` set), just to show that custom styles are not saved in the delta json.

Here is the json for each image:
![Captura de pantalla 2024-07-01 a la(s) 20 41 09](https://github.com/singerdmx/flutter-quill/assets/56521222/bea55957-aea0-4740-a6cb-aa1118d645d0)
`[{insert: asd}]`

![Captura de pantalla 2024-07-01 a la(s) 20 42 38](https://github.com/singerdmx/flutter-quill/assets/56521222/05f4055a-61aa-4428-9dc5-8b1a54887e07)
`[{insert: asd}, {insert: asd, attributes: {color: #FF42A5F5}}, {insert: }]`

Then showing that Json in a new editor in `readOnly` mode without `customStyles` set
![Captura de pantalla 2024-07-01 a la(s) 20 44 16](https://github.com/singerdmx/flutter-quill/assets/56521222/0418047b-c97c-4c98-8c9b-422bd4e7b9f4)


So perhaps as a workaround to save the default styles in the JSON array, I would need to iterate it and insert the "attributes" field with the custom styles for each map that does not contain it. Not sure if that would work and if it would be a desirable solution. Thanks for your help!

**Comment by geronimol** [comment]
New issue #1971
