### ISSUE TITLE
Html render issue with sup and sub

### ISSUE THREAD

**Issue by the-best-is-best** [singerdmx/flutter-quill#1947]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Steps to reproduce

1 - convert data to html and save it
2- return data from html

### Expected results

![Screenshot_1719219662](https://github.com/singerdmx/flutter-quill/assets/72160249/b8675531-2f8e-4469-89ee-719adf2376d0)

### Actual results

![Screenshot_1719219545](https://github.com/singerdmx/flutter-quill/assets/72160249/77deb9c6-e11d-4d63-9418-7e1d08bd78ff)

### Code sample

 controller = QuillController(
                    document: Document.fromHtml(
                        bloc.questions!.question[bloc.currentQuestion].name),
                    selection: const TextSelection.collapsed(offset: 0));

and json  name: "<p>Question 7<sup>2</sup><br/>H<sub>2</sub>O</p>",

**Comment by AtlasAutocode** [comment]
The sub- and super-script issue was addressed in version 9.4 - can you update and verify?

If you must be on an earlier version, then you will need to use special open-type fonts that implement scripting.
The only font I know that implements this is Apple's SF font which can only be used on Apple devices (and only implements for numbers and lower-case English letters!)

**Comment by the-best-is-best** [comment]
I already tested it with the last Version in android not ios and html not supported styling and sup and sub not correct sup need to make text in top not only with small text

**Comment by AtlasAutocode** [comment]
I erroneously assumed that the problem was with rendering sub- and super-scripts in the editor.

The problem appears to be in the html package (published by the dart language team) used to parse html.
It does not seem to recognize the sup and sub html tokens.

**Comment by AtlasAutocode** [comment]
The current code used to import HTML uses html2md which converts html to Markdown and then to Quill Delta.
Since there is no markdown code for sub- and super-script these styles will be ignored.
The only way to solve this problem would be to rewrite the html converter to convert directly to Delta (or json?)
Same answer as Issue 1917

**Comment by the-best-is-best** [comment]
I don't understand but I need to convert it to an html element with all styles

**Comment by AtlasAutocode** [comment]
Yes, I understand what you are trying to do. What you are trying to do is a good and simple idea.
What I am telling you is that the current html converter cannot do what you want and cannot be modified to 'fix' the problem.
The only way would be for you to rewrite the html converter code module so that all html styles are converted.
The only other way will be for you to use json rather than html to set the editor content. That would retain all styles.

I am suggesting a work around.
Change:
>1 - convert data to **html** and save it
2- return data from **html**

To:
>1 - convert data to **json** and save it
2- return data from **json**

**Comment by singerdmx** [comment]
@AtlasAutocode thanks!
