### ISSUE TITLE
Text auto change to list after input -

### ISSUE THREAD

**Issue by haorendashu** [singerdmx/flutter-quill#1949]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.4.6

### Steps to reproduce

In a windows version, after i input ```-``` and a space``` ``` before a new line.

### Expected results

keep input and don't change style.

### Actual results

The editor will auto change to a list style like this:

![liststyle](https://github.com/singerdmx/flutter-quill/assets/1788875/988ebdeb-19c9-4629-a24f-7ca6aa3742c1)

But in mobile version, it not change.

I think in pc and mobile it both shouldn' change the style.

**Comment by AtlasAutocode** [comment]
The style change to a bulleted list appears to be by design.

raw_editor_state.dart includes code to recognize keys '1.' and space at the start of a line and convert it to a numbered list which I think is very intuitive. (I wasn't aware of this shortcut - thank you for pointing it out)
The same code processes hyphen/dash followed by a space and converts to bulleted list which is a little less intuitive but is a convenient way of easily creating bullet lists.

In my testing on windows and android emulator, both behaved the same way.
I have noticed that the characters have to start the line. If you enter the keys space+dash+space it will not be converted. Is it possible that this is why it did not appear to occur on mobile?

If you feel that this conversion should not occur, then perhaps the best option is for you to enter a 'feature request' and the maintainers can review and decide what is best for all.
