### ISSUE TITLE
All font settings are lost when you press Enter twice

### ISSUE THREAD

**Issue by geronimol** [singerdmx/flutter-quill#1969]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

9.5.3

### Steps to reproduce

![Captura de pantalla 2024-07-04 a la(s) 17 42 53](https://github.com/singerdmx/flutter-quill/assets/56521222/3d17c085-1b4e-4551-b1b1-04084c0b029f)

Related issue: #1951

### Expected results

Keep font family and font size after pressing Enter twice

### Actual results

Font family and font size settings are lost pressing Enter twice

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or Video

<details>
<summary>Screenshots / Video demonstration</summary>

![Captura de pantalla 2024-07-04 a la(s) 16 14 40](https://github.com/singerdmx/flutter-quill/assets/56521222/54927dca-05de-4cbe-873a-539c99c9501b)

</details>

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
This is being worked on, but it is more complex than simply pressing enter twice.

To give you an example: 

1. Type text with bold, press enter twice and enter more text - more text is correctly entered as bold.
2. Next, type text with bold, press enter twice then press the **Up-arrow key** and enter more text - more text is NOT entered as bold.

Font and size are treated as inline styles but were not listed in Attribute.inlineKeys. This needs review of Attributes in general.

The problem is in PreserveInlineStylesRule which has a complex interaction between inline and block styles. (see issue 1940)

**Comment by ellet0** [comment]
#1119 could be related.

**Comment by AtlasAutocode** [comment]
Yes, it is related.
The whole business of preserving inline styles is much more complex than I thought it would be.
I have resolved the business of inline styles being maintained when pressing enter (1-many times) but found the styles were lost when you pressed the up-arrow key.

For this issue, I found that font and size were not listed as inline styles. I have fixed this and added tests to ensure the Attribute class collections of keys is updated if new attributes are added in the future (current proposal to add an attribute for linespacing?)

[#1940](https://github.com/singerdmx/flutter-quill/issues/1940) has reported a problem with maintaining inline styles while entering lists or codeblocks. I think I have fixed this as well.

The problem that is still open is editing links. If you click within a link and enter text, the inserted text is inserted as plain text flanked by underscored links. I would think the intent is to edit the visible text for the link rather than splitting the link into 2 parts with plain text?

@ellet0 do you recommend submitting what is done ASAP and worry about what is not fixed later?

**Comment by ellet0** [comment]
> @ellet0 do you recommend submitting what is done ASAP and worry about what is not fixed later?

I recommend releasing changes that fix a bug and cause another as an alpha or experimental version (pub.dev pre-release). Though we no longer maintain the `dev` branch, you also mentioned it's a partial fix for a more complex bug, so I would suggest submitting what has been fixed for now and taking care of the rest later.

**Comment by AtlasAutocode** [comment]
Thanks for your advice.
Have submitted the PR.

**Comment by ellet0** [comment]
> Thanks for your advice.
> Have submitted the PR.

Thank you for your contributions.

**Comment by geronimol** [comment]
Thanks for fixing this!
