### ISSUE TITLE
The tabbar always shows a few selected options

### ISSUE THREAD

**Issue by viet-tran-0159** [singerdmx/flutter-quill#2056]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

tabbar is always displaying a few options. As far as I know it is taking the first character in the editor to display, i just want to show the selected options when I click on the corresponding character, can it be turned off?

![image](https://github.com/user-attachments/assets/69e788a2-4134-4472-8f15-2282dd815e31)

**Comment by AtlasAutocode** [comment]
When you start the editor, no options will be checked.
I assume you checked bold and underline and entered 'gggg'.
Your image shows bold and underlined text which is shown in the toolbar with bold and underline checked.
If you uncheck bold and type some text it will not show bold but will still show underline until you turn it off.
If you then click on the middle 'g' it will again show bold+underline.
The state of the toolbar buttons should reflect where the caret is and what will be seen when you insert text.

**Comment by viet-tran-0159** [comment]
@AtlasAutocode It seems you don't understand my question, let me explain further:
it takes the first character in the editor to display the selected tab bar option
As shown in the image, I have not placed the cursor on the text and it has already been taken to display on the tab bar
One more image to make it easier to understand, if I haven't clicked on the editor, it will take the first character in the editor to show the selected option on the tab bar and if I have selected a character with the selected option on the tab bar, when I When I click out to hide the cursor, the tab bar still retains the selected option even though I have removed the cursor from it

**Comment by AtlasAutocode** [comment]
Thanks for explaining more.
I think the problem might be that, even though the caret is not visible, there is still a selection (where the caret was last placed) and that is used to set the toolbar state.
The controller only has access to the text selection position. Selection is perhaps misleading since typically the 'selection' is zero length and is where the caret will be shown if it is visible when the editor has focus.
When you first open the editor, the selection will be at the start (even if the caret is not visible) and it will therefore show you the state of the first character.
When you click outside the editor, the caret disappears but the selection does not change, and the toolbar state will also not change.
Does this explain what you are seeing?

**Comment by viet-tran-0159** [comment]
@AtlasAutocode 
Your comments are correct
and I realized, because when initializing QuillController, setting the offset for textselection will affect how the option on the tab bar is displayed:
 controller = QuillController(
 document: doccument, 
 selection: const TextSelection.collapsed(offset: 0),   <---- its here

But the problem is when clicking outside the editor, the caret disappears but the selection does not change, and the toolbar state will also not change. I don't know the cause or how to handle it

**Comment by AtlasAutocode** [comment]
> when clicking outside the editor, the caret disappears but the selection does not change

That is correct. The selection does not change because something is always selected. The editor always has something selected (even if collapsed). The visibility of the caret is irrelevant.
I am curious as to why the state of the toolbar matters? What am I missing?
Perhaps you can consider hiding the toolbar when the editor loses the focus?

**Comment by AtlasAutocode** [comment]
There is a PR from @huandu which will automatically hide the toolbar when the editor loses the focus.

**Comment by viet-tran-0159** [comment]
@AtlasAutocode  @huandu 
thanks for noticing my problem
but after applying your PR, i realized the problem is still not solved, i would like to provide the following evidence: the tab bar options are still selected even though i clicked out

https://github.com/user-attachments/assets/6959ba8c-3111-4e8a-9eb4-28da5912b75a

**Comment by huandu** [comment]
@viet-tran-0159 @AtlasAutocode PR #2066 doesn't address this issue; Instead, it fixes the issue in the selection toolbar which is visible after long press or double tap on text.
