### ISSUE TITLE
Link editing error: "type 'Null' is not a subtype of type 'Block' in type cast"

### ISSUE THREAD

**Issue by IWasYourTomb** [singerdmx/flutter-quill#2081]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.1.3

### Steps to reproduce

Tried to edit the link title

### Expected results

Update title

### Actual results

![Снимок экрана 2024-07-31 в 17 14 10](https://github.com/user-attachments/assets/5a1217d4-30df-4176-8669-e9fe5b8ef802)
Error: type 'Null' is not a subtype of type 'Block' in type cast

### Code sample

[Paste your code here]

### Additional Context

[Paste your logs here]

**Comment by AtlasAutocode** [comment]
Can you provide more information?
What is the text in your document?
What is your link?

**Comment by IWasYourTomb** [comment]
https://github.com/user-attachments/assets/5183d2dc-cb5c-45ac-a7d7-3579b0397a91

**Comment by IWasYourTomb** [comment]
> Can you provide more information? What is the text in your document? What is your link?


https://github.com/user-attachments/assets/a4381f1b-5741-4731-8f0e-f51c838e9a2c

**Comment by AtlasAutocode** [comment]
I cannot reproduce the problem on windows desktop or android emulator.
Have you done flutter clean?
If you are running from a debugger, can you get a stack trace - file and line number where the error occurs?

**Comment by IWasYourTomb** [comment]
> I cannot reproduce the problem on windows desktop or android emulator. Have you done flutter clean? If you are running from a debugger, can you get a stack trace - file and line number where the error occurs?

 document.dart at  line 267

**Comment by AtlasAutocode** [comment]
I see there are comments at that location which suggests that whoever wrote that code knew there was a potential problem.
> TODO: prevent user from moving caret after last line-break.
TODO: Can be nullable, handle this case to avoid cast exception.

I cannot fix a problem that I cannot reproduce.
Can you help me understand what you are doing that triggers this problem?
Are you running the flutter-quill example app or is this your own app?

One possibility is that you could be creating an empty document without the required terminal newline. In that case the above error would make sense.

For debugging, we need to know where queryChild is being called from.
I really need to see the stack trace since the problem is somewhere in the calling chain.
What is the value of offset and what is the length of the document?

**Comment by IWasYourTomb** [comment]
> I see there are comments at that location which suggests that whoever wrote that code knew there was a potential problem.
> 
> > TODO: prevent user from moving caret after last line-break.
> > TODO: Can be nullable, handle this case to avoid cast exception.
> 
> I cannot fix a problem that I cannot reproduce. Can you help me understand what you are doing that triggers this problem? Are you running the flutter-quill example app or is this your own app?
> 
> One possibility is that you could be creating an empty document without the required terminal newline. In that case the above error would make sense.
> 
> For debugging, we need to know where queryChild is being called from. I really need to see the stack trace since the problem is somewhere in the calling chain. What is the value of offset and what is the length of the document?

This my own app. I use QuillToolbar.simple for past link
Hope this can help you:

exception = {_TypeError} type 'Null' is not a subtype of type 'Block' in type cast
 _stackTrace = null
 _url = "package:flutter_quill/src/document/document.dart"
 _line = 267
 _column = 9
 _message = "type 'Null' is not a subtype of type 'Block' in type cast"
this = {Document} 
 _root = {Root} ¶ ⟨test⟩link ⏎
 _delta = {Delta} insert⟨ test ⟩ + {link: https://qwe.com}\ninsert⟨ ⏎ ⟩
 _rules = {Rules} 
 documentChangeObserver = {_AsyncBroadcastStreamController} 
 history = {History} 
offset = 6
res = {ChildQuery} 
 node = null
 offset = 0

**Comment by AtlasAutocode** [comment]
> offset = 6

This is the problem as the document length is 5. Doing a queryChild(6) is going off the end of the document.

queryChild is called from many places including updating the state of the toolbar. One of these places is calling the wrong offset for reasons unknown. This is what we need to find to fix the problem.

I suggest you use the debugger and place a breakpoint on the line:
> final block = res.node as Block; // TODO: Can be nullable, handle this case to avoid cast exception

When you hit the breakpoint, you should be able to look at the stack trace and see where the error is being called from.

**Comment by tolotrasamuel** [comment]
I can reproduce this. I am running into the same issue. 

```
======== Exception caught by foundation library ====================================================
The following _TypeError was thrown while dispatching notifications for QuillController:
type 'Null' is not a subtype of type 'Block' in type cast

When the exception was thrown, this was the stack: 
#0      Document.queryChild (package:flutter_quill/src/models/documents/document.dart:254:28)
#1      Document.collectStyle (package:flutter_quill/src/models/documents/document.dart:182:15)
#2      QuillController.getSelectionStyle (package:flutter_quill/src/widgets/quill/quill_controller.dart:121:10)
#3      QuillToolbarToggleStyleButtonState._selectionStyle (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:41:43)
#4      QuillToolbarToggleStyleButtonState.currentStateValue (package:flutter_quill/src/widgets/toolbar/buttons/toggle_style_button.dart:44:47)
#5      QuillToolbarBaseButtonState.didChangeEditingValue.<anonymous closure> (package:flutter_quill/src/widgets/toolbar/base_button/base_value_button.dart:88:35)
#6      State.setState (package:flutter/src/widgets/framework.dart:1203:30)
#7      QuillToolbarBaseButtonState.didChangeEditingValue (package:flutter_quill/src/widgets/toolbar/base_button/base_value_button.dart:88:5)
#8      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
#9      QuillController.replaceText (package:flutter_quill/src/widgets/quill/quill_controller.dart:306:7)
#10     QuillToolbarLinkStyleButtonState._linkSubmitted (package:flutter_quill/src/widgets/toolbar/buttons/link_style_button.dart:166:9)
#11     QuillToolbarLinkStyleButtonState._openLinkDialog (package:flutter_quill/src/widgets/toolbar/buttons/link_style_button.dart:146:5)
<asynchronous suspension>
The QuillController sending notification was: Instance of 'QuillController'
================================================================================
```

**Comment by AtlasAutocode** [comment]
@tolotrasamuel Thank you for the stack trace - most helpful and it's always good to know someone else can reproduce a problem. Any clues on how I can reproduce the problem?

> QuillToolbarLinkStyleButtonState._linkSubmitted

This method does not exist in the current code. From the source code path, it appears you are using an old version. Can you update to the current version 10 and see if the problem persists? There have been many changes to the code recently.

Based on the stack trace, my guess is that there is something wrong with the content of the link. Are there any language issues, such as multiple character codes or hidden characters that could be causing string length to be miscalculated? What is the minimum set of operations that trigger the problem? Sorry to be so vague, but without being able to reproduce the problem, I can only make suggestions.
> If your debugging skills are good, you can use the stack trace to step back through the code to find the point at which the queryChild offset is miscalculated.

I have been able to trigger an exception by the following steps:
1. Enter a link
2. Select/highlight all of the link
3. Edit the link and **shorten** the text for the link
4. assert fails because the prior range of the selection is longer than the current text

This does not explain the current issue, but it does show how complex the code is (and not always correct, unfortunately). This is why it is important to carefully document the minimum set of operations that trigger the problem. Equally important is the similar steps that DO NOT trigger the problem. The solution is somewhere in between.

**Comment by stepushchik** [comment]
Version 10.1.10
The same error when try `final Style style = _quillController.getSelectionStyle();`

```
type 'Null' is not a subtype of type 'Block' in type cast:
                 #0      Document.queryChild (package:flutter_quill/src/document/document.dart:271:9)
                 #1      Document.collectStyle (package:flutter_quill/src/document/document.dart:184:15)
                 #2      QuillController.getSelectionStyle (package:flutter_quill/src/controller/quill_controller.dart:150:10)
```

**Comment by AtlasAutocode** [comment]
Yes, we know **_where_** the error is.
We do not know **_why_** the error is.
Since queryChild is called from numerous places, the consequence of returning an invalid result is simply going to cause a problem elsewhere that is going to be harder to fix.

I need to know what your document content is and what is selected - this is causing an error condition **before** you call the function and that is what we need to fix.

I am currently working on a number of problems with handling of links. Links are handled differently from all other attributes and cause many problems. If you can tell me how to reproduce your problem, I can test my fixes.
