### ISSUE TITLE
How to change color of disabled icons in toolbar menu ?

### ISSUE THREAD

**Issue by Mmisiek** [singerdmx/flutter-quill#2091]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

How to change color of disabled icons in toolbar menu ? I found way to change active icon color but disabled stay grey or oposite of active ? 

In Light Theme I see all.

<img width="1141" alt="image" src="https://github.com/user-attachments/assets/cc6696c3-74e8-4b13-8be8-86db9014df14">

In Dark Theme disabled icons and separators are gone.

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/f93e7985-69dc-46af-99cb-88da2d0e5e77">

**Comment by AtlasAutocode** [comment]
Many of the toolbar buttons are derived from QuillToolbarIconButton which creates the icon buttons on the toolbar. One of the members is:
> disabledColor: iconTheme?.iconButtonUnselectedData?.disabledColor,

iconTheme can be set from the button options (but that is a pain since there does not appear to be a global setting). In the absence of setting a value, the code will use the default. 

QuillToolbarIconButton  creates the button by calling IconButton and the comments on disabledColor may provide you a way to set your disabled buttons color.

  >/// The color to use for the icon inside the button, if the icon is disabled.
  /// Defaults to the **[ThemeData.disabledColor]** of the current [Theme].
  ///
  /// The icon is disabled if [onPressed] is null.
  final Color? disabledColor;

I don't know if this will work for the dividers, but you can see if you can set your global theme

**Comment by Mmisiek** [comment]
Thanks for suggestion. Somehow disabledColor was not working for me instead disabledForgoundColor in style worked:
`   iconButtonUnselectedData: quill.IconButtonData(
                            style: IconButton.styleFrom(
                              foregroundColor: Config().darkMode()
                                  ? Colors.white
                                  : Colors.black,
                              disabledForegroundColor: Config().darkMode()
                                  ? Colors.red
                                  : Colors.yellow,
                            ),`

**Comment by Mmisiek** [comment]
For dividers use:
`                    sectionDividerColor:
                        Config().darkMode() ? Colors.white : Colors.black,`
