### ISSUE TITLE
Keep dash in lists in toPlainText

### ISSUE THREAD

**Issue by bloemy7** [singerdmx/flutter-quill#2101]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### The question

Hi,

I am using the `document.toPlainText` method to go from delta to plain text, but when I have text that contains lists, this strips away the dashes in the list too, i.e:
```
- first item
- second item
```

gets converted to just 
```
first item
second item
```

Is there any way to override the behavior so we can keep the dashes here? Thanks!

**Comment by AtlasAutocode** [comment]
Unfortunately, lists are not text and are stored as block attributes on the newline symbol. The deltas do not contain dashes and toPlainText will not include them.

Bullet lists are rendered in a platform dependent fashion - on yours as dashes, on windows desktop as round dots.

The toPlainText methods have optional parameters to handle conversion of embed objects. I suspect you are going to need to add another parameter to enable custom handling of nodes.

There is a simpler possibility: Do not use lists and enter plain text with dashes. Your display will look the same, but your plain text output will include dashes since they are actually text in the document. (If you want to explore this: set enableMarkdownStyleConversion = false in QuillEditorConfigurations)

**Comment by bloemy7** [comment]
Thanks for the ideas here, appreciate it!
