### ISSUE TITLE
Should we add a spellchecker for Editor?

### ISSUE THREAD

**Issue by CatHood0** [singerdmx/flutter-quill#2108]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

Should we add a `SpellChecker` for the editor?  What do you think about this feature?

I think this can be possible adding [spell_check_on_client](https://github.com/ivofernandes/spell_check_on_client) that makes more easy get suggestions and splitting wrong words from the right words and it doesn't need a internet connection. 

_I'll take some time to start this feature since this is complex to add to the editor._

**Comment by EchoEllet** [comment]
Since we don't have many tests, I prefer it if this feature is optional and separated to avoid breaking existing features and causing regressions. The features that were added recently to the project caused some minor bugs.

Spellcheck might not always work or might not support all languages. We could also consider making such features easier to implement by documenting the code and making it more extensible.

There are different providers for spellcheck that validate the spelling.

You can implement this feature into the project if you want.

**Comment by CatHood0** [comment]
> I prefer it if this feature is optional

I think the same thing. Since this feature could give some bugs to the editor ans should be experimental for now. I probably add this to it's own package or directly add it to the `flutter_quill_extensions`.
