### ISSUE TITLE
HashTag and see more functionality 

### ISSUE THREAD

**Issue by FarrukhFaraz** [singerdmx/flutter-quill#2160]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Use case

How can we handle HashTag (@, #) functionality in Quill Editor.
How can we add see more options if text is more than specific lines

### Proposal

Please add HashTag tag functionality to editor as it mostly used in social Media Apps.

Anyone please suggest me as I have these new requirements in my flutter app using flutter_quill editor as already it is handling a lot of functionality.

**Comment by EchoEllet** [comment]
Thank you for the report, we currently do have a lot of issues to process as such we're unable to add this feature, it also requires some changes to different places.

We plan to separate such features as an extension package since they often conflict with other features, and they are not standard for all use cases.

An example in Quill JS is [quill-mention](https://github.com/quill-mention/quill-mention).

**Comment by EchoEllet** [comment]
Though this is not a feature yet, it seems like it's possible to implement. See #1330.
