### ISSUE TITLE
Spellcheck example doesn't work on web

### ISSUE THREAD

**Issue by DevTard** [singerdmx/flutter-quill#2164]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.4.8

### Steps to reproduce

1. Clone Example
2. Run the code 
3. Type incorrectly

### Expected results

Spellchecker would work

### Actual results

Nothing happens, the check code is never called

### Code sample

See example

### Additional Context

It's annoying that you removed the spellchecker and created an example that doesn't work.

**Comment by CatHood0** [comment]
Which is the language that are you using when test the example app?

**Comment by CatHood0** [comment]
Please, provide to me a video of example of what is happening while you type something (i could guess what is the error)

**Comment by DevTard** [comment]
I'm testing in English. 

Here's a video - there's no error it just doesn't do anything

https://github.com/user-attachments/assets/cd55b24d-1ab5-4e19-bbf1-7e766f3e7e6e

**Comment by CatHood0** [comment]
You test this on Desktop? I mean, for the Desktop example app instead the web? I think could something from the web (i'll check why this could be happening on web)

**Comment by DevTard** [comment]
The example does run at all on Mobile or Desktop for me. But using the same code in my own project it works on mobile, but not on web - so seems to be platform specific

**Comment by CatHood0** [comment]
@AtlasAutocode do you have any idea why this could be happening just in Web?

**Comment by AtlasAutocode** [comment]
Sorry, I never use Web.
If I had to guess, I would suspect something like the Paste problem that prevents external access because of security concerns.

**Comment by CatHood0** [comment]
@DevTard I'm sorry, but I have no idea how to fix this problem. For now I'll leave this open and then someone who knows can help us with this.

**Comment by EchoEllet** [comment]
Testing `simple_spell_checker` outside of `QuillEditor` and seems to be working, however `isWrong` seems to be reversed.

```dart
final result = spellChecker.checkBuilder<Widget>('An examplo here',
        builder: (word, isWrong) {
      return Text(word, style: TextStyle(color: isWrong ? Colors.red : null));
    });
```

![image](https://github.com/user-attachments/assets/88be50d6-8a21-4e37-803d-80a735c8f65f)

However, I'm not sure how the 80 MB dictionary files will load on the web when deployed, especially for users with slow connections.

**Comment by CatHood0** [comment]
@EchoEllet yeah, i need to change that part of the examples in the README because itshould be called "`isValid`" since the implementation of the word checking was renamed and changed.

**Comment by EchoEllet** [comment]
> It's annoying that you removed the spellchecker and created an example that doesn't work.

Thank you for the feedback, we moved it since it was not ideal for other users as it increased the size to about 80 MB. Not all users are interested in this feature so we initially decided to move it into its own package and we didn't since our implementation is not ready and we haven't had the time to fix it for now.

For Android and iOS, this issue will be solved with platform API. For web, I'm interested into knowing how this issue will be solved.

Even if it did work, 80 MB is quite a lot to load for your users so there will be more issues when deploying the app.

Does the browser have its own Spell checking service that is supported on most known browsers?

One way of solving it is to publish packages for each dictionary language and include only the ones you need, which will require more maintenance, and more setup by complicating the usages and some breaking changes.

**Comment by CatHood0** [comment]
This issue was fixed at the last version of the package. But, by now, we suggest not using SpellCheckerService by now until we have a stable implementation.
