### ISSUE TITLE
Show  context menu toolbar on single tap up

### ISSUE THREAD

**Issue by dashuaiqin** [singerdmx/flutter-quill#2177]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.5

### Steps to reproduce

The toolbar appears when the textfield is clicked once in flutter, but not when the quillEditor is clicked

### Expected results

Show toolbar 

### Actual results

 toolbar will not show

**Comment by singerdmx** [comment]
Does 10.5.4 have this issue?

**Comment by dashuaiqin** [comment]
Yes, there is this problem too.
but the toolbar will appear when you click the cursor on the normal textfield

**Comment by AtlasAutocode** [comment]
On mobile, the copy-paste toolbar will only popup when you make a selection (long-press).
Single tap would be used to move the caret so you can enter more text at a new position. In that case, wouldn't it be annoying to have a popup appear since you would have to keep closing it?
I don't program for mobile so I don't know why single tap on a text field would give you a context menu. Is this normal?

**Comment by dashuaiqin** [comment]
I mean, click the position of the cursor on the ios side (just one click) to display the toolbar, just like this.

发自我的iPhone


------------------ Original ------------------
From: AtlasAutocode ***@***.***&gt;
Date: Tue,Sep 3,2024 9:25 PM
To: singerdmx/flutter-quill ***@***.***&gt;
Cc: Wolffy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [singerdmx/flutter-quill] Show  context menu toolbar on singletap up (Issue #2177)





 
On mobile, the copy-paste toolbar will only popup when you make a selection (long-press).
 Single tap would be used to move the caret so you can enter more text at a new position. In that case, wouldn't it be annoying to have a popup appear since you would have to keep closing it?
 I don't program for mobile so I don't know why single tap on a text field would give you a context menu. Is this normal?

**Comment by dashuaiqin** [comment]
https://github.com/user-attachments/assets/3e40aabf-d092-4958-bf05-492bdad40cf3

**Comment by AtlasAutocode** [comment]
Flutter-Quill does not have this concept.

I tried the Mail app on my iPad, and it also does not act in the way you are wanting. (I get no popup, and the cursor is positioned for adding text just like QuillEditor.)
I tried the Text app on an iPhone, and it gave a response like you are looking for.
So, it seems like this is a custom action rather than an expected result.

I am changing this issue to an _enhancement_ rather than a _bug_ to encourage contributors to look into how this could be done.

**Comment by dashuaiqin** [comment]
OK, thank you.



发自我的iPhone


------------------ Original ------------------
From: AtlasAutocode ***@***.***&gt;
Date: Tue,Sep 3,2024 10:19 PM
To: singerdmx/flutter-quill ***@***.***&gt;
Cc: Wolffy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [singerdmx/flutter-quill] Show  context menu toolbar on singletap up (Issue #2177)





 
Flutter-Quill does not have this concept.
 
I tried the Mail app on my iPad, and it also does not act in the way you are wanting. (I get no popup, and the cursor is positioned for adding text just like QuillEditor.)
 I tried the Text app on an iPhone, and it gave a response like you are looking for.
 So, it seems like this is a custom action rather than an expected result.
 
I am changing this issue to an enhancement rather than a bug to encourage contributors to look into how this could be done.

**Comment by EchoEllet** [comment]
@singerdmx Why is this issue closed?
