### ISSUE TITLE
Unable to Delete Heading 1 at the Beginning of a Line with Backspace

### ISSUE THREAD

**Issue by agata** [singerdmx/flutter-quill#2180]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.5

### Steps to reproduce

1. Apply Heading 1 to the first line.
2. Enter some text.
3. Delete the text using the Backspace key.
4. Continue deleting the space after the text is gone.

### Expected results

The Heading 1 style should be removed, and the text should revert to normal formatting.

### Actual results

The Heading 1 style is not removed and remains applied. Although the toolbar shows that the text has reverted to normal, the Heading 1 style is still applied, and any new text entered continues to be formatted with Heading 1.

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Additional Context

This issue has been confirmed on macOS, iOS, and Android.

<details>
<summary>Screenshots / Video demonstration</summary>

https://github.com/user-attachments/assets/dc42e782-5bdb-42d9-af6e-2854dcdc0d34

</details>

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by AtlasAutocode** [comment]
Sorry but we seem to have had a collision over this issue.

I just submitted a PR that simply resolves this problem with minimal changes to raw_editor_actions (line101) consistent with the method used for inline styles.
But I did not realize that you had just submitted a PR using delete rules and raw_editor_state.

Unfortunately, your changes block my changes, so we need to resolve the differences.
As far as I can see, your changes correctly address the backspace removal of style but do not update the toolbar state which still shows header3 active.

If I comment out your call to `_handleBackspaceKey` the code now removes the heading style and updates the toolbar state. It appears that your handling of the backspace is preventing my updating of the toolbar state.

Can you look into this and see how we can handle the conflict?
Thank you.

**Comment by agata** [comment]
@AtlasAutocode 

I have confirmed the operation. By commenting out _handleBackspaceKey, your changes work perfectly. It also functions correctly for deleting inline elements, and I particularly like the behavior where text inside a block is not deleted if it remains.

I will submit a pull request to revert this pull request. Thank you.

**Comment by AtlasAutocode** [comment]
Thank you for your kind words.
I again apologize - the fault was mine.
I look forward to working with you in the future.

**Comment by agata** [comment]
@AtlasAutocode 

This improvement only works on the desktop version. On iPhone, even though the toolbar reverts to the normal style when pressing backspace, the header style is not removed. Upon investigation, it seems that the QuillEditorDeleteTextAction is not triggered on mobile devices. Do you have any idea what might be causing this?

**Comment by AtlasAutocode** [comment]
Interesting: Running an android emulator, when I use the computer's keyboard, everything works correctly. However, when I use the emulator's keyboard it fails. There must be something peculiar about the keyboard handler.

Another anomaly is: select header1 and enter text. Remove the text using BS on the emulator's keyboard. As soon as the last character is removed, the toolbar loses the header state. This state should be **retained and only removed** when you press BS one more time. Because this attribute is lost too soon, the code to process the extra BS does not call formatText and QuillEditorDeleteTextAction. This is probably the reason for the failure.

Strangely no other block attribute has this effect. Alignments and lists all work correctly, but font settings (headers, fonts, and line height) all fail. That makes no sense.

I'm tied up with other things at the moment but will try to take another look and dig deeper to see if I can figure out what is happening here.

**Comment by agata** [comment]
This issue might be related.

https://github.com/flutter/flutter/issues/142882

**Comment by agata** [comment]
The following issue might also be related. It seems that in Flutter, there is no way to handle the delete key event on mobile keyboards.

https://github.com/flutter/flutter/issues/128926

**Comment by AtlasAutocode** [comment]
Those posts are very disappointing. How can Flutter be taken seriously when such errors exist?

At present, I am stuck. I had to reinstall Android Studio to fix an unrelated problem. Now, there is an incompatibility between gradle and java because of the latest Android Studio (Ladybug) release which is causing everyone problems!

What this all means is I cannot even build for Android let alone try to figure out what is going on with this issue.

It will probably be faster if you look into this.

The key observations are:
1. When the last character is removed, the toolbar state changes and is incorrect:
2. State is incorrectly removed for:
a.  Inline attributes: font (maybe size but didn't check)
b. Block attributes: Header, line height

Other inline and block attributes work correctly with the backspace on the soft keyboard.

**Comment by EchoEllet** [comment]
> At present, I am stuck. I had to reinstall Android Studio to fix an unrelated problem. Now, there is an incompatibility between gradle and java because of the latest Android Studio (Ladybug) release which is causing everyone problems!
> 
> What this all means is I cannot even build for Android let alone try to figure out what is going on with this issue.

Fixed the issue in #2312 for the example app.

Also, see [this comment](https://github.com/flutter/flutter/issues/156282#issuecomment-2395457663).
