### ISSUE TITLE
`QuillEditorConfigurations.enableMarkdownStyleConversion` not respected

### ISSUE THREAD

**Issue by vishna** [singerdmx/flutter-quill#2214]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.5.16

### Steps to reproduce

Platform: iOS/Android

1. Open example app
2. Open empty document
3. Type `1. ` (space included) __USE SOFTWARE KEYBOARD__

### Expected results

The `1.` is turned into ordered list

### Actual results

The `1.` remains an ordinary text

### Additional Context

I've looked into the bit where the auto formatting should happen:

`_onKeyEvent` > `_handleSpaceKey`

https://github.com/singerdmx/flutter-quill/blob/master/lib/src/editor/raw_editor/raw_editor_state.dart#L790

The problem is `_onKeyEvent` is never getting triggered. 

It could be https://github.com/singerdmx/flutter-quill/issues/2039 is related .

**Comment by CatHood0** [comment]
#2039 it's an different type error caused by the rendering. I'll fixing it yet since is not a simple issue.

**Comment by CatHood0** [comment]
We need to take a look why now `_onKeyEvent` is not being triggered.

**Comment by CatHood0** [comment]
Unfortunately, this is a platform limitation of Android.

On-screen keyboards aren't hardware keyboards, and aren't required to simulate hardware keyboard events. The fact that you are able to type into a text field is because there is a text InputConnection between an on-screen application that simulates a keyboard from touch events, and it converts those key presses into text input editing requests, not hardware keyboard events: no keyboard events are ever created, so none can be handled.

Although it seems like an obvious thing to try, converting from InputConnection editing events to keyboard events is a non-deterministic mapping, since, for instance, we don't know which physical keys were pressed to send the characters in the editing event, so we can't just simulate them from input connection events, and we wouldn't get any key up events either.

If you attach an actual hardware keyboard to the Android device, or use an on-screen keyboard that does happen to simulate hardware keyboard events (there are some that do, but sadly not the default GBoard), then the events will be handled.

**Comment by vishna** [comment]
@CatHood0 while these events might not available on iOS/Android it should still be possible to make enableMarkdownStyleConversion work on those platforms.

I kinda need this so I'll try to implement it 😓

**Comment by CatHood0** [comment]
Can be implemented. But, some parts of the editor need to change. You can see [AppFlowy shortcuts implementation](https://github.com/AppFlowy-IO/appflowy-editor/blob/main/documentation/customizing.md)

**Comment by EchoEllet** [comment]
> can you confirm this?

AFAIK, iOS does have keyboard events (at least in native iOS). Same in Android, it's a bit tricky and requires some workarounds but it should be possible. If it's not possible directly using Flutter then it will require platform code (Kotlin and Swift)
