### ISSUE TITLE
A new line still remains part of the link.

### ISSUE THREAD

**Issue by JoepHeijnen** [singerdmx/flutter-quill#2241]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.6.3

### Steps to reproduce

1. Focus the quill editor
2. Type https://google.com
3. Press new line
4. Type Hello

### Expected results

The word "Hello" should not be part of the link.

### Actual results

The word "Hello" is part of the link.

**Comment by AtlasAutocode** [comment]
I cannot reproduce this issue on desktop. 'Hello' is not part of the link.
What platform are you using?
Is there any other text in your document?
When you are about to press <enter> what is the status of the link toolbar button?
Any other information that would help me to reproduce this issue?

**Comment by madoka3530** [comment]
iOS / Andriod mobile app is remain.

**Comment by AtlasAutocode** [comment]
Thanks for the information.
I tried using an Android emulator and still cannot reproduce the problem.

Can you run the flutter quill example app and see if you get the same problem? This way we will be running the same code and should get the same result.
The key observation is that after entering the link with the dialog, the link toolbar button should not be lit up. In my case it is not, but in your video it is.

My best guess is your code is doing _something_ that we are not expecting, and we are not handling this correctly. We just need to find out what that _something_ is.

**Comment by JoepHeijnen** [comment]
My apologies. I wasn’t paying attention to which version of flutter_quill I was running. I thought it was the latest version, but it turned out to be 10.1.5. This bug has been fixed in version 10.2.0 (https://github.com/singerdmx/flutter-quill/pull/2114). Apologies again for the inconvenience. I will close this issue.

**Comment by AtlasAutocode** [comment]
Thank you for letting us know the problem is solved.
(I also have trouble keeping track of versions!)

**Comment by AtlasAutocode** [comment]
> We might consider changing the release workflow and also not publishing versions on daily basis.

I agree. The only downside is that contributors could be submitting fixes that conflict with pending PRs.
I've learnt to check pending PRs, but I have still made mistakes.

I think your suggestions are correct: Once an issue is confirmed as a bug, someone should assign themselves and then it (should be) visible to everyone that it is being worked on. But do people actually check for existing issues before submitting a new issue?

One other thought: If there was a **stable** (master?) branch for everyone and a **working** branch for contributors, we could always find conflicts. Working could be pushed to stable on a weekly(?) basis.

**Comment by EchoEllet** [comment]
> I The only downside is that contributors could be submitting fixes that conflict with pending PRs.

It depends on the changes, for my PRs it usually requires very little effort, if a significant change was made in a file then the other should know before introducing a change and then having conflict that requires more effort and check than usual.

> But do people actually check for existing issues before submitting a new issue?

Some of them don't If we're familiar with the issue, we can close it as duplicated and then redirect the submitter to the original issue.

> One other thought: If there was a stable (master?) branch for everyone and a working branch for contributors, we could always find conflicts. Working could be pushed to stable on a weekly(?) basis.

The code base itself is not stable yet, even if we have a branch called `stable`, I suggested previously in different issues and threads, (see #2269) to only accept critical bug fixes, new code quality changes, tests, docs, and bug fixes will be in `dev` branch, new features will usually no longer accepted, especially those like such as markdown conventions for mobile, soft keyboard or youtube support, table or hashtag/mention, we can have exceptions but we should discuss it first, and should be clear to all contributors before they put the effort and time and then reject their changes simply because it's not a PR issue.

Features like Flutter/WASM are important for most users and should be supported when possible.

I think it's important to create more issues and discussions all in one place, I have repeated this at least 20 times across different unrelated issues. We should not lose track of suggestions and things to handle, we have discussed many things in previous issues or PRs but never created their own issue, resulting into completely losing them.

Contributors sometimes don't explain their changes and their changes are not self-explanatory either, if you take a look at my changes in 2023 you will notice I did something very similar, however, I have cleaned at least most of them and still solving issues. This is not something everyone does which is why I don't want to merge things that we don't understand (regardless of the reason) and then contact contributors after a while asking them about their changes.
