### ISSUE TITLE
Build failure on Windows/Android related to flutter_inappwebview and flutter_inappwebview_windows when using flutter_quill_extensions

### ISSUE THREAD

**Issue by AtlasAutocode** [singerdmx/flutter-quill#2280]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)

### Flutter Quill version

10.7.5

### Steps to reproduce

1. Android Studio, Terminal
2. flutter build windows

Or:
1. Select Target
2. Run Debug

### Expected results

App compiles or runs

### Actual results

**Nuget is not installed.**
```console
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: The command "setlocal [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: NUGET-NOTFOUND install Microsoft.Windows.ImplementationLibrary -Version 1.0.231216.1 -ExcludeVersion -OutputDirectory C:/Flutter/GitHub/flutter-quill/example/build/windows/x64/packages [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: NUGET-NOTFOUND install Microsoft.Web.WebView2 -Version 1.0.2210.55 -ExcludeVersion -OutputDirectory C:/Flutter/GitHub/flutter-quill/example/build/windows/x64/packages [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: NUGET-NOTFOUND install nlohmann.json -Version 3.11.2 -ExcludeVersion -OutputDirectory C:/Flutter/GitHub/flutter-quill/example/build/windows/x64/packages [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmEnd [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmErrorLevel [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: exit /b %1 [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :cmDone [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :VCEnd" exited with code 9009. [C:\Flutter\GitHub\flutter-quill\example\build\windows\x64\plugins\flutter_inappwebview_windows\flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj]
Building Windows application...                                    839ms
Build process failed.
```

### Additional Context

Other flutter apps compile with no problem so something has happened in my fork of Flutter Quill.
Other apps that use Flutter-Quill run without problem,
flutter build web succeeds
I had no problems yesterday with 10.7.3

Something broke but I have no idea what or how to fix it!
Anyone know how to install Nuget on Android Studio?

**Comment by EchoEllet** [comment]
Flutter CLI already automate this but just to confirm do you have this [change](https://github.com/singerdmx/flutter-quill/pull/2230/commits/e1b0eb3b927dbcde5c7e87388cf63c115b3fca2e) in the example?

See all changes [between 10.7.3 and 10.7.5](https://github.com/singerdmx/flutter-quill/compare/v10.7.3...v10.7.5). I have never heard of Nugest before in native Android or Flutter Android apps. A quick search indicate that's for .NET projects.

Can you try running the app without `flutter_quill_extensions` since it uses plugins that use `flutter_inappwebview`. Could be related to [flutter_inappwebview_windows](https://pub.dev/packages/flutter_inappwebview_windows) since it has been added recently (33 hours ago).

**Comment by AtlasAutocode** [comment]
That makes sense. My other app that uses Flutter-Quill does not include extensions and the error message does refer to inappwebview.
Why it should be trying to use Nuget is a mystery and my inability to run on Android makes no sense. Running on web is also inconsistent.
Will check when I get back to my main computer.

**Comment by EchoEllet** [comment]
That's the one reason why I suggest to discount the support of YouTube video player in #2276

Having heavy dependency only to load YouTube iframe embeds on desktop/mobile is not ideal. If it's aginst the terms of service of YouTube then that gives us a reason to not support it as a default when a user asks for this feature built-in.

**Comment by EchoEllet** [comment]
The question is that we never updated the dependencies of `flutter_quill_extensions` in the last 32 hours to use the new version that include `flutter_inappwebview_windows` as a default implementation, so:

- Why would it cause issues on the Android app?
- And how was it included without updating anything? Unless I'm missing something, we don't have CI workflow that update the dependencies to their latest major version if available. When running the app on macOS/Linux or any platform, the Windows example runner is always getting updated and I do revert the changes of in-app webview in #2230. This branch is open before `flutter_inappwebview_windows` getting published.

**Comment by AtlasAutocode** [comment]
> Flutter CLI already automate this but just to confirm do you have this [change](https://github.com/singerdmx/flutter-quill/pull/2230/commits/e1b0eb3b927dbcde5c7e87388cf63c115b3fca2e) in the example?

Confirmed.
> That's one reason why I suggest discounting the support of the YouTube video player in https://github.com/singerdmx/flutter-quill/issues/2276

I agree. We should not get in the middle of this. 
Again, your concept of an API provides the ability of users to add a plug-in of what they want without affecting how the QuillEditor works. Maintainability and reliability.

I tried opening the `flutter_inappwebview_windows_DEPENDENCIES_DOWNLOAD.vcxproj` in Visual Studio and it failed to build.
The error was `Cannot open include file: 'nlohmann/json.hpp': No such file or directory`
This is consistent with NuGet failing to install the json package.
Another error was:  `Cannot open include file: 'WebView2.h': No such file or directory`
I have no idea where this comes from.

Another error was: `The command "setlocal NUGET-NOTFOUND install Microsoft.Windows.ImplementationLibrary -Version 1.0.231216.1 -ExcludeVersion -OutputDirectory C:/Flutter/GitHub/flutter-quill/example/build/windows/x64/packages`
I assume `NUGET-NOTFOUND` is part of the command line because of the previous failure to download the json nuget package

I tried using the VS package manager to install the Newtonsoft Json Nuget package and it failed:
`Could not install package 'Newtonsoft.Json 13.0.3'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Is it possible   'native,Version=v**0.0**'   might be the problem?

I retried to build in VS but selected Release build x64. Same result. 4 projects succeeded and 2 failed.

**Comment by EchoEllet** [comment]
Seems like a Windows platform-specific issue which I'm not familiar with or with **Visual Studio** though thank you for the details. While fixing #1192 I had another build failure issue caused by [flutter_inappwebview_macos](https://pub.dev/packages/flutter_inappwebview_macos) on macOS.

Don't really what happened, we never updated the dependencies of `flutter_quill_extensions` for the last 3 months and its desktop macOS and Windows support was introduced yesterday in [flutter_inappwebview 6.1.0](https://github.com/pichillilorenzo/flutter_inappwebview/releases/tag/v6.1.0).

Will need to check if this example specific issue or can happen on the new minimal empty flutter project.

If it's not an example issue, I will probably introduce a breaking change in `flutter_quill_extensions` and remove [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) in a minor version or maybe having `11.0.0` ASAP, having it backward compatible require fork of `youtube_player_flutter` and our own implementation in `quill_native_bridge` of webview platform views for a feature that shouldn't be in `flutter_quill_extensions`. 

The main reason I'm working on #2230 is to introduce a minor version removing `super_clipboard` without any noticeable breaking changes.

**Comment by EchoEllet** [comment]
Seems like a Windows platform-specific issue which I'm not familiar with or with **Visual Studio** though thank you for the details. While fixing #1192 I had another build failure issue caused by [flutter_inappwebview_macos](https://pub.dev/packages/flutter_inappwebview_macos) on macOS.

Don't really what happened, we never updated the dependencies of `flutter_quill_extensions` for the last 3 months, and desktop macOS and Windows support was introduced yesterday in [flutter_inappwebview 6.1.0](https://github.com/pichillilorenzo/flutter_inappwebview/releases/tag/v6.1.0).

Will need to check if this example specific issue or can happen on the new minimal empty flutter project.

If it's not an example issue, we might consider introducing a breaking change in `flutter_quill_extensions` and remove [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) in a minor version or maybe having `11.0.0` ASAP, having it backward compatible require fork of `youtube_player_flutter` and our own implementation in `quill_native_bridge` of webview platform views for a feature that shouldn't be in `flutter_quill_extensions`. 

The main reason I'm working on #2230 is to introduce a minor version removing `super_clipboard` without any noticeable breaking changes.

**Comment by EchoEllet** [comment]
I'm unfamiliar with or with **Visual Studio** and native Windows platform though thank you for the details. While fixing #1192 I had another build failure issue caused by [flutter_inappwebview_macos](https://pub.dev/packages/flutter_inappwebview_macos) on macOS.

Don't really know what happened, we have never updated the dependencies of `flutter_quill_extensions` for the last 3 months, and desktop macOS and Windows support was introduced yesterday in [flutter_inappwebview 6.1.0](https://github.com/pichillilorenzo/flutter_inappwebview/releases/tag/v6.1.0). So I'm not sure why [flutter_inappwebview_macos](https://pub.dev/packages/flutter_inappwebview_macos) or [flutter_inappwebview_windows](https://pub.dev/packages/flutter_inappwebview_windows) are dependencies.

Will need to check if this example specific issue or can happen on the new minimal empty flutter project.

If it's not an example issue, we might consider introducing a breaking change in `flutter_quill_extensions` and remove [youtube_player_flutter](https://pub.dev/packages/youtube_player_flutter) in a minor version or maybe having `11.0.0` ASAP to avoid such issues, having it backward compatible require fork of `youtube_player_flutter` and our own implementation in `quill_native_bridge` of webview platform views for a feature that shouldn't be part of `flutter_quill_extensions` Instead it should be possible to Implement, see #2276.

The main reason I'm working on #2230 is to introduce a minor version removing `super_clipboard` without any noticeable breaking changes.

**Comment by EchoEllet** [comment]
Does including the following in your `pubspec.yaml` (of the app package) fix the issue?

```yaml
dependency_overrides:
  youtube_player_flutter: 9.0.4
  flutter_inappwebview: 6.1.0
```

**Comment by AtlasAutocode** [comment]
Added to example pubspec.yaml (was this correct?)
```
  dependency_overrides:
    youtube_player_flutter: 9.0.4
    flutter_inappwebview: 6.1.0
```
Did not resolve problem - still cannot build on windows.

I switched to my app that uses QuillEditor: build on Windows = OK.
Added flutter-quill_extensions - build fails.
Added the overrides - build still fails.

Looking at flutter_inappwebview, it looks like they have a lot of problems. There were 26 pending PRs and more than a thousand issues.

I could not see where inappwebview was being invoked from. I assume it is being brought in by code to support web viewing on windows?

Going back to the FQ example app:
Changed version to:  flutter_inappwebview: **6.0.0**
Now builds OK, so the problem was introduced by inappwebview when they added support for windows.

I will try to figure out what the problem is with inappwebview but I assume that it will be that their windows module needs work. But it should not prevent building.

**Comment by EchoEllet** [comment]
> (was this correct?)

Actually, this is incorrect, windows support was introduced in `6.1.0`, use the following instead:

```yaml
dependency_overrides:
  youtube_player_flutter: 9.0.4
  flutter_inappwebview: 6.0.0
```

Can you confirm the version that's used for `youtube_player_flutter`, `flutter_inappwebview`, and `flutter_inappwebview_windows` by running:

```shell
flutter pub deps
```

And see if the issue still exist.

**Comment by AtlasAutocode** [comment]
Yes, I tried 6.0.0 and it built OK.

I downloaded the inappwebview package:
Their example app built when the target was Edge (browser).
Their example app failed when the target was Windows (desktop).
I filed an issue to see if they can address the problem and was able to give them the error messages. It looks like a CMake version problem.

**Comment by EchoEllet** [comment]
Should be fixed in [10.8.0](https://github.com/singerdmx/flutter-quill/releases/tag/v10.8.0). Can you try and see the latest version?

**Comment by AtlasAutocode** [comment]
Helpful contact from the author of the inappwebview package.

```
nuget needs to be accessible from the command line and
it is not sufficient to have it available through Visual Studio.
```
#### For the benefit of those experiencing this problem with building on Windows:

- nuget download Instructions:  https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools?tabs=windows#nugetexe-cli
- Move nuget.exe to a location on the command PATH

Now compiles with no problems.

**Comment by EchoEllet** [comment]
Sure but those are additional steps we're trying to avoid when we don't have a reason to require, should be able to build the app with the latest version without requiring `nuget` in the system PATH, this instruction should be documented in `README.m`, the error itself should be more specific and more simple, I think it's possible that they can check the system PATH and see if `nugest` is in the system path before throwing error that's very generic and require day to solve, I have saw some clipboard plugins that require configuring `AndroidManifest` (which is required even on native apps in this case) but doesn't check or see if it's configured or a proper way to see the missing the configuration, this is handled in `quill_native_bridge`. The error message is clearer and provides instructions to solve this common issue and will be removed in the production build, javascript is dynamic language and there is a requirement on web to include a script in `index.html`, and even though it has been for a while now, we're still getting reports about such issues in this repo when we already included this instruction in `README.md`, I prefer better error message that's more specific that make tracing the issue easier.
