### ISSUE TITLE
[Web] Keyboard arrow keys does not work inside a ScrollView

### ISSUE THREAD

**Issue by wliumelb** [singerdmx/flutter-quill#304]
When the QuillEditor is a child of SingleChildScrollView, cannot move the cursor with keyboard arrow keys.

**Comment by singerdmx** [comment]
Don't make it a child of SingleChildScrollView
Not our problem

**Comment by wliumelb** [comment]
Found a workaround: 

Wrap QuillEditor with a RawKeyboardListener to intercept KeyEvent and prevent it from propagating to parents.

````
SingleChildScrollView(
        child: RawKeyboardListener(
              onKey: (RawKeyEvent event) {},
              focusNode: FocusNode(onKey: (FocusNode node, RawKeyEvent event) {
                  return KeyEventResult.skipRemainingHandlers;
              }),
              child: QuillEditor(
                    ...
              ),
       ),
)
````

**Comment by jagrut-18** [comment]
> Found a workaround:
> 
> Wrap QuillEditor with a RawKeyboardListener to intercept KeyEvent and prevent it from propagating to parents.
> 
> ```
> SingleChildScrollView(
>         child: RawKeyboardListener(
>               onKey: (RawKeyEvent event) {},
>               focusNode: FocusNode(onKey: (FocusNode node, RawKeyEvent event) {
>                   return KeyEventResult.skipRemainingHandlers;
>               }),
>               child: QuillEditor(
>                     ...
>               ),
>        ),
> )
> ```

I was trying to create shortcuts to toggle bold and italic using `FocusableActionDetector`. But because of this workaround, I think the shortcut events are not triggered. I was thinking, it would be a really nice option to provide `actions` and `shortcuts` directly from the library.

Or can anyone suggest another approach to create shortcuts while using the editor?
