### ISSUE TITLE
[Mobile] [IOS] Quill Cursor took the initial position & style when tab anywhere after the first time and start typing.

### ISSUE THREAD

**Issue by AkshayJainX** [singerdmx/flutter-quill#581]
### Discussed in https://github.com/singerdmx/flutter-quill/discussions/554

<div type='discussions-op-text'>

<sup>Originally posted by **akshayindia** December 26, 2021</sup>
My issue is about [Mobile] with IOS. I'm facing an issue with IOS 15. **Also, the issue started when quill upgraded to the Flutter 2.8 version.**

I have tried running the `example` directory successfully before creating an issue here. 

When I placed the cursor for the first time, it works. But when I placed it for the next time and start typing. It starts from the last cursor position. I've added the video of the error.

Do let me know if you've any queries. 

Flutter & Dart Version - 
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (9 days ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

https://user-images.githubusercontent.com/36562389/147393980-452cfae4-40ae-47ff-bb12-79e0aa635309.mov

</div>

**Comment by akshayindia** [comment]
Hi @singerdmx, @cbracken, @rish07, @yzxben, @jonmountjoy, 

This issue still persists in IOS 15 for flutter_quill: ^3.2.0 version.

Also, I found that issue is with the external keyword. So what I found is that when I type through the iPhone soft keyword it works but when I use the mac keyword to type in the IOS simulator the issue exists.
