### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by luckygogreen** [singerdmx/flutter-quill#642]
**My issue is about [Mobile]

dev_dependencies:
       flutter_quill: ^3.9.4 

It's full of bugs. It doesn't work。

[.../android/app/src/debug/AndroidManifest.xml]() Error:
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [:gallery_saver] [.../build/gallery_saver/intermediates/library_manifest/debug/AndroidManifest.xml]() as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="carnegietechnologies.gallery_saver" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [:gallery_saver] [.../build/gallery_saver/intermediates/library_manifest/debug/AndroidManifest.xml]() as the library might be using APIs not available in 19
  	Suggestion: use a compatible library with a minSdk of at most 19,**

**Comment by matthiasn** [comment]
@luckygogreen I don't think it is fair to say that this library is full of bugs. My experience is quite the opposite, the library works really well, with just an occasional edge case that doesn't work, with very responsive maintainer and authors when that happens.

For your issue, have you tried the suggestions? What happens if you follow the suggestions?
