### ISSUE TITLE
Font size dropdown?

### ISSUE THREAD

**Issue by mark8044** [singerdmx/flutter-quill#785]
Right now it seems like any changes to font size has to be done with Header H1, H2, H3 tags.  But I see there is a working font size functionality that accepts double or int (https://github.com/singerdmx/flutter-quill/pull/487/commits/0c3fb6ff1a90bbb68f1f183a63e34f784ce657a6).  That one works very well

Is it possible to get a drop down selector to directly select font sizes (eg. 12, 13, 14, 15, 16, 17, etc..)

**Comment by adrian-moisa** [comment]
@mark8044 Not a lead dev here, just commenting from the side. This can be planned as a future feature. I suppose for the moment the desire was to have as few taps as necessary. At the moment if you really want multiple selection of styles in a dropdown you will have to implement a custom Toolbar that recycles all the buttons from the existing one and then add the dropdown yourself wherever you want it. Fortunately each single button from the Toolbar is encapsulated in it's own Widget so they can be easily reused. On the other editor side you can override the default styles using the `customStyleBuilder` property in `QuillEditor`. At some point in time I might spend time on this feature since I desire it myself for my own project. Also something nice to have would be the ability to switch between several styles. If you want to hear updates on the progress join the unofficial [Quill discord](https://discord.gg/XpGygmXde4) server that I run. 

Ex:

```
  DefaultStyles _quillStyles() => DefaultStyles(
        paragraph: _textStyle(),
        placeHolder: _textStyle(
          overrideColor: widget.placeholderColor,
        ),
        h1: DefaultTextBlockStyle(
          TextStyle(
            fontSize: 28,
            color: _theme.mainTextColor,
            height: 1.7,
            fontWeight: FontWeight.w600,
          ),
          const Tuple2(70, 20),
          const Tuple2(0, 0),
          null,
        ),
      );
```

**Comment by mark8044** [comment]
> 

Thanks for the reply!  I'm not meaning multiple selection of styles, but a new button, similar to say the Bold or Italic button, except it would give a `font-size` to the text.  `Font-size` is already fully functional within quill, it just needs a button to be able to access it.  In this case, the button would ideally present some kind of drop-down with choices.  

I guess that brings up a side question, do we have the ability to add our own buttons in?

**Comment by adrian-moisa** [comment]
Not sure if in the default Toolbar but for sure you can create a new toolbar using the existing buttons + new custom buttons

**Comment by mark8044** [comment]
> Not sure if in the default Toolbar but for sure you can create a new toolbar using the existing buttons + new custom buttons

Yes that's 100% possible, but it seems like it should be integrated into flutter_quill since the core functionality is already there and works wonderfully.

@singerdmx If I *try* to make a pull request with a separate font-size dropdown widget, would you be against merging that into flutter_quill?

**Comment by singerdmx** [comment]
Go ahead

**Comment by mark8044** [comment]
@singerdmx 

Hi I think I have gotten it to work.   
I am just finalizing a few things to give user ability to input the range of values they want, it should only take a short little while longer.

I saw that `class QuillDropdownButton` is marked as depreciated, so I refactored it for this purpose and I'm using it successfully here, are you ok with that?

**Comment by mark8044** [comment]
Ok I aded this pull request, lets see what you all think. https://github.com/singerdmx/flutter-quill/pull/790

**Comment by mark8044** [comment]
Ok it got merged 🥇
