### ISSUE TITLE
[Mobile] difficulty adjusting text selection from left to right

### ISSUE THREAD

**Issue by jonasbernardo** [singerdmx/flutter-quill#793]
My issue is about [Mobile]

in version 4.1.6 after selecting the text, when trying to adjust the selection from left to right it doesn't work right, it takes a lot of work to adjust from left to right.
the opposite from right to left adjusts without problems

**Comment by adrian-moisa** [comment]
Can you describe in greater detail what are you doing? Which device? Is the problem visible in other platforms? The more information the better.

**Comment by jonasbernardo** [comment]
this video I made from an app I made using the flutter quill package showing the problem foun

https://user-images.githubusercontent.com/22117346/167251631-5c9dd405-f59b-4087-9544-a4dd25e52d6f.mp4

**Comment by adrian-moisa** [comment]
@jonasbernardo That's a very interesting setup you got there. By watching what you did with the handlers it seems that they go out of bounds of the parent and the hit testing algo cannot resolve their position. That's a rather peculiar thing to happen because as far as I know the handles are drawn in an overlay. Which means it should be touchable even outside of the parent region. I'm not sure what is the upper structure of your app. I'd suggest. Try placing a random touchable element in one of the quadrants (slightly outside and in an overlay) to see if it still touch sensitive. If it is not it means the problem belongs to your layout. If it is then it must be Quill. though from here on my advice runs short. All I can say is you can start putting some breakpoints/logs in Quill starting with this region: 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/11160141/167297016-f95322ba-2bb4-4b96-a48b-e49a3dd3c0b0.png">
To see what happens. If you want to bounce more ideas join the [unofficial discord](https://discord.gg/XpGygmXde4). There's already a handful of people that are active in Quill. One of us might have an idea. Cheers!

**Comment by jonasbernardo** [comment]
I managed to solve it in part, it was my misuse problem
