### ISSUE TITLE
Creating views that contain math equation such as: sqrt,... (using latex expression or others)

### ISSUE THREAD

**Issue by ThatPham2000** [singerdmx/flutter-quill#961]
Your package is great. 
Besides, I want to create math expressions and chemistry expressions, ... However, I have encountered this problem.
I cannot find any document. Thanks for supporting.

**Comment by SSebigo** [comment]
There is support for formulas, it should work by setting the param to ```true``` in the toolbar and using an embed builder. It doesn't seem to work on web, tho.

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.

**Comment by Sairam-Suresh** [comment]
Hey everyone,
I would just like to check if there is built-in support for formulas (e.g Latex) in the flutter_quill_extensions package, as the readme says that there is support for formulas but I am unable to figure out a way to activate it. Unfortunately I also could not find documentation to set up Formula support in the Flutter Quill Editor. It would be great if someone could point me in the right direction regarding this, thanks everyone.

(I apologise in advance if this comment is out of place, I decided to comment here since this issue already exists)
