### ISSUE TITLE
image pick is not supported in Web

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [singerdmx/flutter-quill#976]
My issue is about Web platform

I have tried running `[flutter_quill example]` (https://github.com/singerdmx/flutter-quill/tree/master/example) 
The error occurred in **### getApplicationDocumentsDirectory**
```
  Future<String> onImagePickCallback(File file) async {
    // Copies the picked file from temporary cache to applications directory
    final appDocDir = await getApplicationDocumentsDirectory();
    final copiedFile =
        await file.copy('${appDocDir.path}/${basename(file.path)}');
    return copiedFile.path.toString();
  }
```

i'm user latest version of flutter and of the plugin
`flutter 3.3.4, flutter_quill: ^6.0.8+1`

any other solution?

**Comment by true2thepen** [comment]
Still issue on flutter 3.3.7 and flutter_quill 6.1.3

**Comment by LuchoTurtle** [comment]
This.
This won't ever work on the `web` because [`path_provider` ](https://pub.dev/packages/path_provider) does *not support* it. 
So, it fails when calling `getApplicationDocumentsDirectory()`.

Using [`universal_io`](https://pub.dev/packages/universal_io) might work to create a file from the array of bytes of the chosen image file.

**Comment by hectorAguero** [comment]
I think this is a old issue, there's no need for universal_io, flutter_quill already has a `webImagePickImpl` property, also universal_io doesnt work for that. https://github.com/singerdmx/flutter-quill/blob/5dca6008cde707beb46291b6fbf71af6dbbf7bfb/example/lib/pages/home_page.dart#L272C29

Still, using the https://pub.dev/packages/cross_file will be better that ask for a webImplementation.

**Comment by LuchoTurtle** [comment]
@hectorAguero sure, `cross_file` might be a better option. But uploading images does not work on the web when running the `example` app, even when `webImagePickImpl` is initialized.
This is because `onImagePickCallback` is called after the callback the code is executed in `webImagePickImpl`. So, the file that you return from `webImagePickImpl` will be passed on to `onImagePickCallback` 😞

**Comment by freshtechtips** [comment]
Thank you for the report, this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
