### ISSUE TITLE
[Web] insert an image url manually

### ISSUE THREAD

**Issue by MohammedSalehelShazly** [singerdmx/flutter-quill#977]
[Web]
How to insert an image url manually
I'm trying to use this way..
```
controller.document.insert(100, const Embeddable(
  'image',
  'https://user-images.githubusercontent.com/10923085/119221946-2de89000-baf2-11eb-8285-68168a78c658.png',
),
```
but the previous line was removed and throw an exception .. `Index out of range: index must not be negative: -1`

**Comment by churchnotesapp** [comment]
This worked fine for me when I used 1 instead of 100

`IconButton(
             icon: Icon(
                        Icons.photo_camera,
                        color: Theme.of(context).accentColor,
                        size: 22,
                      ),
            onPressed: () => contentController!.document.insert(1, const quill.Embeddable(
  'image',
  'https://user-images.githubusercontent.com/10923085/119221946-2de89000-baf2-11eb-8285-68168a78c658.png',
),
          )))`

**Comment by freshtechtips** [comment]
Thank you for the report,
We have recently added extension function that help you inserting images
 this issue has been open for a while and since there are no interactions with it, we had to close it

but if you still facing this issue, or other issues or you have any other questions, feel free to contact us anytime you want.
